### ISSUE TITLE
批量删除时生成的sql过于复杂

### ISSUE THREAD

**Issue by 3zengzz** [yangzhongke/Zack.EFCore.Batch#101]
代码如下所示
  public class TestDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optcionsBuilder)
        {
            var conn = "server=xxxx;port=3305;uid=root;pwd=xxxx;database=evoc9_person";
            optcionsBuilder.UseMySql(conn, ServerVersion.AutoDetect(conn));
            optcionsBuilder.UseBatchEF_MySQLPomelo();
            optcionsBuilder.LogTo(efEvent =>
            {
                Console.WriteLine(efEvent);
            }, LogLevel.Information);

            base.OnConfiguring(optcionsBuilder);
        }

    static async Task Main(string[] args)
      {
            var idList = new List<long> { 1466292886873182208, 1466327495824510976 };
            var dbContext = new TestDbContext();

            var rows = await dbContext.DeleteRangeAsync<PsPerson>(s => s.PersonId == 0);
    }

生成的sql如下
info: 2022/12/7 15:15:40.125 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 6.0.9 initialized 'TestDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql:6.0.2' with options: ServerVersion 8.0.28-mysql
dbug: 2022/12/7 15:15:40.822 CoreEventId.QueryExecutionPlanned[10107] (Microsoft.EntityFrameworkCore.Query)
      Delete FROM `ps_person` WHERE `PersonId` IN(SELECT `PersonId` FROM (SELECT `p`.`PersonId`
      FROM `ps_person` AS `p`
      WHERE `p`.`PersonId` = 0)  AS  temp1 )

0

**Comment by yangzhongke** [comment]
抱歉，我这个只是在hack的方式用EFCore的SQL生成机制，所以没有找到生成最简化的SQL的方法，如果您发现了，欢迎贡献PR。

**Comment by 3zengzz** [comment]
您好，你发的邮件，我已收到，谢谢！
