### ISSUE TITLE
在继承自DbContext的ApplicationDbContext中无法使用扩展方法

### ISSUE THREAD

**Issue by Lkingself** [yangzhongke/Zack.EFCore.Batch#103]
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
            
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseBatchEF_MSSQL();
        }
}
await dbContext.BatchUpdate<Product>(s => CompareP2Porject(s, rows));使用扩展方法时会报错

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS1929	“ApplicationDbContext”不包含“BatchUpdate”的定义，并且最佳扩展方法重载“BatchEFExtensions.BatchUpdate<Product>(DbSet<Product>, DbContext)”需要类型为“DbSet<Product>”的接收器	BlazorApp2.Server	C:\Users\Administrator\source\repos\BlazorApp2\BlazorApp2\Server\Controllers\SampleDataController.cs	149	活动

**Comment by yangzhongke** [comment]
注意通过泛型指定实体类型
![image](https://user-images.githubusercontent.com/13821363/209091204-aa636905-5e84-4041-9dfd-0cf5aa232b58.png)

**Comment by Lkingself** [comment]
![image](https://user-images.githubusercontent.com/25604345/209095764-01683144-c828-45eb-9447-4d26b50eacd9.png)
这样还是会报相同的错误
![image](https://user-images.githubusercontent.com/25604345/209095835-bcaf49ff-7170-48a0-afd9-66d377eda17a.png)

**Comment by yangzhongke** [comment]
这是BatchUpdate方法的两个重载方法签名：
public static BatchUpdateBuilder<TEntity> BatchUpdate<TEntity>(this DbContext ctx) where TEntity:class
 public static BatchUpdateBuilder<TEntity> BatchUpdate<TEntity>(this DbSet<TEntity> dbSet, DbContext ctx) where TEntity : class
你看着情况自己解决吧。估计你用的不是最新版的组件。

**Comment by Lkingself** [comment]
收到杨工，非常感谢，已解决，现在有个这样的问题
dbContext.BatchUpdate<Product>() .Set(s => s.ProjectTime, s =>TestMethod(s.DeviceId)) .Execute();
string TestMethod(string code)
        {
            return code + "xxx";
        }
杨工，在第二个参数中传入方法，这样似乎无法获得TestMethod返回的值，而是获得参数的值，这可以通过什么方法解决吗。

**Comment by yangzhongke** [comment]
EFCore的翻译引擎的机制决定了无法在lambda表达式里写自定义方法，除非你自己写Custom Functions

**Comment by Lkingself** [comment]
好吧，非常感谢杨工

**Comment by Lkingself** [comment]
杨工，如果想要批量复杂更新数据库，还有什么好的方法吗
更新方法我是这样写的
var rows = MiniExcel.Query<MonthProject>(path).Where(s=>s.ProjectDate!=null).ToList();
var products = dbContext.Products.Where(s => s.ProductId != null);
foreach (var product in products)
                            {
                                CompareP2Porject(product, rows);
                            }
                            await dbContext.SaveChangesAsync();
```
private void CompareP2Porject(Product product,List<MonthProject> projects)
        {
            var productCodeList = new List<int>();
            var productCodeSplits = product.DeviceId.Split("-");
            var productCharPart = productCodeSplits[0] + "-" + productCodeSplits[1];
            if(productCodeSplits.Count()==3)
                productCodeList = Enumerable.Range(Convert.ToInt32(productCodeSplits[2]), 1).ToList();
            else
                productCodeList = Enumerable.Range(Convert.ToInt32(productCodeSplits[2]), Convert.ToInt32(productCodeSplits[3])- Convert.ToInt32(productCodeSplits[2])+1).ToList();
            for (int i = 0; i < projects.Count(); i++)
            {
                var projectCodeSplits = projects[i].ProductionOrder.Split("-");
                var prjectCodeList = new List<int>();
                var projectCharPart = projectCodeSplits[0] + "-" + projectCodeSplits[1];
                if (projectCodeSplits.Count() == 3)
                    prjectCodeList = Enumerable.Range(Convert.ToInt32(projectCodeSplits[2]), 1).ToList();
                else
                    prjectCodeList = Enumerable.Range(Convert.ToInt32(projectCodeSplits[2]), Convert.ToInt32(projectCodeSplits[3])- Convert.ToInt32(projectCodeSplits[2])+1).ToList();
                if (productCharPart == projectCharPart && productCodeList.Intersect(prjectCodeList).Any())
                {
                    product.ProjectTime = projects[i].ProjectDate;
                    product.Workshop = projects[i].Workshop;
                    break;
                }
            }
        }

这样更新数据量小的时候可以，数据量变大后就无法进行更新了，我用的是Blazor wasm hosted

**Comment by yangzhongke** [comment]
你这样比较复杂的更新规则只能一条条更新了。
