### ISSUE TITLE
使用步骤2UseBatchEF_MSSQL()会报错

### ISSUE THREAD

**Issue by yupeiyong** [yangzhongke/Zack.EFCore.Batch#104]
杨老师，我用的是Ef core7 数据库是Sqlserver,如果使用下面的步骤2会报错，如果不使用则能正常使用，数据也新增成功了，是哪里有什么问题吗？
Step 2:

Depending on the database, add the following code into OnConfiguring() method of your DbContext respectively.

optionsBuilder.UseBatchEF_MSSQL();// as for MSSQL Server

**Comment by yangzhongke** [comment]
![image](https://user-images.githubusercontent.com/13821363/210917365-394cddd2-880d-4e05-931e-c99e1663e910.png)

**Comment by yupeiyong** [comment]
ok,thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangzhongke/Zack.EFCore.Batch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月6日(星期五) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangzhongke/Zack.EFCore.Batch] 使用步骤2UseBatchEF_MSSQL()会报错 (Issue #104)
