### ISSUE TITLE
批量修改可空时间类型异常

### ISSUE THREAD

**Issue by shaoqilan** [yangzhongke/Zack.EFCore.Batch#105]
批量修改可空时间类型异常：
![image](https://user-images.githubusercontent.com/29734798/215970722-0177dd65-10ce-4784-8fef-2de5d8245d94.png)
具体写法
xxx.BatchUpdate().Where(p => p.RelateOrderNo == orderInfo.OrderNo).Set(p=> p.UseTime, useTime).Execute()
p.UseTime类型为DateTime?   
useTime类型为DateTime
数据库字段
![image](https://user-images.githubusercontent.com/29734798/215971049-df7063e6-ff97-440f-b2a6-187cf3894194.png)

**Comment by yangzhongke** [comment]
抱歉，我这里无法重现这个bug，请给出一个最简单的可以重现问题的独立项目

![image](https://user-images.githubusercontent.com/13821363/216239008-6cae551f-f76c-4dfb-9ce2-381f800dfe16.png)

**Comment by yangzhongke** [comment]
你用普通的linq操作，比如ctx.Products.Where(x.UseTime==useTime).ToArray();看是否运行正常。如果这个运行正常，那就是我的库的问题，但是需要你提供一个能重现问题的步骤，包括.NET的版本,EFCore的版本，SQLServer的版本。
如果这个也运行不正常，那就不是我的库的问题了。

**Comment by yangzhongke** [comment]
SQLServer日期类型用datetime2试试。
