### ISSUE TITLE
批量插入2万条数据报错

### ISSUE THREAD

**Issue by zhengwei1219** [yangzhongke/Zack.EFCore.Batch#108]
文档：Zack.EFCore.Batch.MySQL.Pomelo批量插...
链接：http://note.youdao.com/noteshare?id=35d1b13c0c1a53b95f187b1755cf13c6&sub=A3003EF9E05242369CE53A040C2EDDB1

插入5000条数据没有问题，数据量为2万时报错：Message:An error occurred using a transaction.
详情见文档

**Comment by yangzhongke** [comment]
试着把BulkInsert放到SaveChanges之后试试。如果还不行，请提供完整的异常堆栈，而不只是提供一部分。

**Comment by yangzhongke** [comment]
不太清楚具体原因。我的猜测是执行超时造成的。你可以试着调整一下DbContext的超时时间相关的参数。刚发布的新版中，我也为BulkInsert增加了一个int ? bulkCopyTimeoutInSecond = null参数，代表超时的秒数。你自己琢磨着试试吧。
如果还不行，你就把批量插入这部分不用我的库，而是直接用MySqlBulkCopy重写，如果还有问题，你就向Mysql efcore的库提Issue吧。

**Comment by zhengwei1219** [comment]
修改后已可以批量插入，感谢杨老师：       
         CancellationTokenSource cts = new CancellationTokenSource();
                cts.CancelAfter(360000000);
                var context = await _monthlyDetailService.GetDbContextAsync();

                var tran = context.Database.CurrentTransaction.GetDbTransaction();
                context.BulkInsert(monthlyDetailList, tran as MySqlConnector.MySqlTransaction, cts.Token);
