### ISSUE TITLE
Deleting based on Navigation Properties generates wrong SQL Statement

### ISSUE THREAD

**Issue by JoshC94** [yangzhongke/Zack.EFCore.Batch#11]
Hi,

I'm using EfCore with MSSQL and i'm trying to delete records belonging to a particular entity, however when I use DeleteRangeAsync it seems to skip the whole path of properties and just treats the last property as if it belonged to the root object.

The relations are like this:
User <1:N> License
License <1:N> Environment

Now when i DeleteRangeAsync:
```
await _dbContext.DeleteRangeAsync<Environment>(e => e.License.User.Id == id);
await _dbContext.DeleteRangeAsync<License>(l => l.User.Id == id);
```
it leads to the following output in SQL Server Profiler
```
exec sp_executesql N'Delete FROM [Environments] WHERE [Id] = @__id_0',N'@__id_0 bigint',@__id_0=3
exec sp_executesql N'Delete FROM [Licenses] WHERE [Id] = @__id_0',N'@__id_0 bigint',@__id_0=3
```
So it basically compares the provided id to Environment.Id and License.Id respectively, whereas the statements should actually look something like this:
```
DELETE env
FROM Environments AS env
INNER JOIN Licenses AS lic ON lic.Id = env.LicenseId
WHERE lic.UserId = 3;

DELETE FROM Licenses WHERE UserId = 3;
```

Would be great if we could find a solution for this. Thanks!

Best Regards,

Josh

**Comment by yangzhongke** [comment]
Thanks for your feedback. I'll try to fix it.
This issue is difficult to solve, so it may take many days before it's fixed.

**Comment by yangzhongke** [comment]
Bug fixed, please update to the latest version.
Please let me know the result.

**Comment by JoshC94** [comment]
Thanks for the fast fix, awesome!

The example from above now results in these commands:
```sql
Delete
FROM [Environments]
WHERE Id IN(
    SELECT Id
    FROM (
        SELECT [e].[Id], [e].[LicenseId], [e].[Name]
        FROM [Environments] AS [e]
        LEFT JOIN (
            SELECT [l].[Id], [l].[UserId]
            FROM [Licenses] AS [l]
            WHERE [l].[Type] = N'xxx' -- This Condition is because of TPH Inheritance
        ) AS [t] ON [e].[LicenseId] = [t].[Id]
        LEFT JOIN [Users] AS [u] ON [t].[UserId] = [u].[Id]
        WHERE [u].[Id] = @__id_0
    )  AS  Vb2d8dceec5c8429da7e3964e019f4778
)

Delete
FROM [Licenses]
WHERE Id IN(
    SELECT Id
    FROM (
        SELECT [l].[Id], [l].[Active], [l].[Expires], [l].[Type], [l].[UserId], [l].[SystemId], [l].[TenantId]
        FROM [Licenses] AS [l]
        LEFT JOIN [Users] AS [u] ON [l].[UserId] = [u].[Id]
        WHERE [u].[Id] = @__id_0
    )  AS  Ve33a65af098547e5b18edc15227849d4
)
```

So as you can see, it does what it should. Maybe it could be tweaked in the future, to get rid of some of these subselects, but for now i'm more than happy.
Thanks a lot!
