### ISSUE TITLE
OracleBulkCopy 可以通过 BulkCopyTimeout 设置超时时间

### ISSUE THREAD

**Issue by hjslovehr** [yangzhongke/Zack.EFCore.Batch#110]
这是我拉取源代码调试的

```
private static OracleBulkCopy BuildSqlBulkCopy<TEntity>(OracleConnection conn, DbContext dbCtx, OracleBulkCopyOptions copyOptions) where TEntity : class
        {
            var dbSet = dbCtx.Set<TEntity>();
            var entityType = dbSet.EntityType;
            var dbProps = BulkInsertUtils.ParseDbProps<TEntity>(dbCtx, entityType);

            OracleBulkCopy bulkCopy = new OracleBulkCopy(conn, copyOptions);
            bulkCopy.BulkCopyTimeout = 360; // timeout unit: second

            bulkCopy.DestinationTableName = entityType.GetTableName();
            foreach (var dbProp in dbProps)
            {
                string columnName = dbProp.ColumnName;
                bulkCopy.ColumnMappings.Add(columnName, columnName);
            }
            return bulkCopy;
        }
```

设置 BulkCopyTimeout 可以解决我的超时问题。可否考虑将这个属性加到这个方法的参数列表中。
谢谢！

[OracleBulkCopy.BulkCopyTimeout](https://docs.oracle.com/cd/E11882_01/win.112/e23174/OracleBulkCopyClass.htm#CHDEBDDF)

**Comment by yangzhongke** [comment]
已完成。请更新到最新版。
![image](https://user-images.githubusercontent.com/13821363/218908536-4a38ecfb-75f0-457a-8329-065b8c931ad7.png)

另外，这个库也支持.NET 7 &Oracle了。

**Comment by hjslovehr** [comment]
谢谢！
太好了，我赶紧去试试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangzhongke/Zack.EFCore.Batch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月15日(星期三) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangzhongke/Zack.EFCore.Batch] OracleBulkCopy 可以通过 BulkCopyTimeout 设置超时时间 (Issue #110)





 
已完成。请更新到最新版。
 
 
另外，这个库也支持.NET 7 &amp;Oracle了。
