### ISSUE TITLE
当我添加  optionsBuilder.UseBatchEF_MSSQL();后 启动任意接口都报下面错误

### ISSUE THREAD

**Issue by songmeimei** [yangzhongke/Zack.EFCore.Batch#112]
System.TypeLoadException: Method 'GetCommand' in type 'Zack.EFCore.Batch.MSSQL.Internal.ZackQuerySqlGenerator_MSSQL' from assembly 'Zack.EFCore.Batch.MSSQL_NET6, Version=6.1.4.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by yangzhongke** [comment]
![image](https://user-images.githubusercontent.com/13821363/222661306-37241190-76f4-447e-9e1b-045d4adc1e30.png)
