### ISSUE TITLE
是否支持 .net6 达梦数据库？

### ISSUE THREAD

**Issue by louislu007** [yangzhongke/Zack.EFCore.Batch#114]

**Comment by yangzhongke** [comment]
抱歉，达梦的.net 6的nuget包没有传到nuget.org，所以我没法支持。你如果是达梦的客户，你可以催他们把包传上来，而不是自己搞一个包

**Comment by louislu007** [comment]
官网已经提供达梦的.net6包下载，杨老师是否可以升级对达梦的支持?
https://download.dameng.com/eco-file-server/file/eco/download/20221009191638UFZC4K8TUU9A0O8ACL

[EFCore.Dm6.0.zip](https://github.com/yangzhongke/Zack.EFCore.Batch/files/14940308/EFCore.Dm6.0.zip)

**Comment by yangzhongke** [comment]
达梦的包没有放到Nuget上，所以很难支持。

**Comment by louislu007** [comment]
nuget上已经有了，请看以下地址
https://www.nuget.org/packages/DM.Microsoft.EntityFrameworkCore/6.0.0.20604

**Comment by yangzhongke** [comment]
抱歉，说错了，有DM的.net6支持，不过用的达梦EFCore版本不是官方的
https://www.nuget.org/packages/ZackEFCore.Batch.Dm_NET6
