### ISSUE TITLE
BatchUpdate时报错：The given key '__ef_filter__p_0' was not present in the dictionary

### ISSUE THREAD

**Issue by zhengwei1219** [yangzhongke/Zack.EFCore.Batch#115]
var star = Convert.ToDateTime(BalanceDate);
               var queryupdate = context.BatchUpdate<ReadySettleDetail>()

                          .Set(a => a.SettleFlag, a => 1)
                          .Set(a => a.Status, a => ReadySettleStatusEnum.Settle)
                          .Set(a => a.SettledOn, a => star)
                           .Where(a => a.CreationTime > Convert.ToDateTime(input.StartDate) && a.CreationTime <= Convert.ToDateTime(input.BalanceDate) && a.SettleFlag == 0);

               await queryupdate.ExecuteAsync();

**Comment by yangzhongke** [comment]
https://github.com/yangzhongke/Zack.EFCore.Batch/issues/76

**Comment by zhengwei1219** [comment]
我系统中已用的是最新的包了：Zack.EFCore.Batch.MySQL.Pomelo   1.6.4

**Comment by yangzhongke** [comment]
那你试试这个吧。
https://github.com/yangzhongke/Zack.EFCore.Batch/issues/17

**Comment by zhengwei1219** [comment]
感谢，使用了.ExecuteAsync(ignoreQueryFilters: true);确实有效，我的项目是用的abpvnext。在底层加入了过滤条件的原因

**Comment by zhengwei1219** [comment]
还请教一个问题，如何将这个更新方法和我的插入方法放在同一个事物中。我知道插入方法可以传入当前事物，更新方法可以吗？

**Comment by yangzhongke** [comment]
你用EF Core标准的事务使用方式就行，如果启用了EFCore事务，更新、删除都默认应用EF Core的事务。
批量插入方法中有一个MySqlTransaction参数，可以用来显式传递事务参数对象。
