### ISSUE TITLE
[BUG] Bulk Insert .Net7 doesn't handle enumerations

### ISSUE THREAD

**Issue by RHaughton** [yangzhongke/Zack.EFCore.Batch#118]
Hi, 
I have 65k records to inserts. I tried this library in .NET7 but my enumeration field is 0 everywhere.

Is this a known bug? Can we do something about it?

Thanks for your help

**Comment by yangzhongke** [comment]
Could you provide a project that can reproduce the problem?

**Comment by RHaughton** [comment]
This is the object im trying to persist.

```
public class MyDbObject : Item
{
    public required Number TaxonomyAlignedRev { get; set; }
}
```

the Number class is a owned type

```
public class Number {
    public TValue? Value { get; set; }
    public DataStatus Status { get; set; }
}
```

The Enum which is causing a problem
```
public enum DataStatus
{
    [Name("Ok")] Ok = 0,
    [Name("Not Collected")] NotCollected = 1,
    [Name("Not Applicable")] NotApplicable = 2,
    [Name("Not Disclosed")] NotDisclosed = 3,
    [Name("Not Meaningful")] NotMeaningful = 4,
    [Name("No Information")] NoInformation = 5,
    SdsAligned = 6
}
```

When I use the bulk insert all my datastatus are 0. which is the default

**Comment by yangzhongke** [comment]
Sorry. owned type is not supported.
