### ISSUE TITLE
Is there a way to delete with a limit?

### ISSUE THREAD

**Issue by CliffCawley** [yangzhongke/Zack.EFCore.Batch#12]
For example with other libraries in the past I've used:

```
            await _context.MyTable
                .Where(x => x.Started < expireDate)
                .Take(50)
                .DeleteAsync();
```

Is something like this possible?

**Comment by yangzhongke** [comment]
Thanks for your advice.
It is not supported at this time, but I will make it possible today.
Just a moment please.

**Comment by yangzhongke** [comment]
Done.
Please update the package to the latest version.
## Take(), Skip()
Take() and Skip() can be used to limit the affected rows of DeleteRangeAsync and BatchUpdate:
```CSharp
await ctx.Comments.Where(c => c.Article.Id == id).Skip(3).DeleteRangeAsync<Comment>(ctx);
await ctx.Comments.Where(c => c.Article.Id == id).Skip(3).Take(10).DeleteRangeAsync<Comment>(ctx);
await ctx.Comments.Where(c => c.Article.Id == id).Take(10).DeleteRangeAsync<Comment>(ctx);

await ctx.BatchUpdate<Comment>().Set(c => c.Message, c => c.Message + "abc")
	.Where(c => c.Article.Id == id)
	.Skip(3)
	.ExecuteAsync();

await ctx.BatchUpdate<Comment>().Set(c => c.Message, c => c.Message + "abc")
	.Where(c => c.Article.Id == id)
	.Skip(3)
	.Take(10)
	.ExecuteAsync();
await ctx.BatchUpdate<Comment>().Set(c => c.Message, c => c.Message + "abc")
   .Where(c => c.Article.Id == id)
   .Take(10)
   .ExecuteAsync();
```

If it works well, please let me know.

**Comment by CliffCawley** [comment]
This one doesn't work for me:
`await ctx.Comments.Where(c => c.Article.Id == id).Take(10).DeleteRangeAsync<Comment>(ctx);`

It generates SQL like:
`Delete FROM [Comments] WHERE ([Article.Id] = id)`

(It doesn't use the limit)

**Comment by yangzhongke** [comment]
> This one doesn't work for me:
> `await ctx.Comments.Where(c => c.Article.Id == id).Take(10).DeleteRangeAsync<Comment>(ctx);`
> 
> It generates SQL like:
> `Delete FROM [Comments] WHERE ([Article.Id] = id)`
> 
> (It doesn't use the limit)

Have you updated the package to the latest version 1.4.5?
It works for me.
```
      Delete FROM [T_Comments] WHERE [PKId] IN(SELECT [PKId] FROM (SELECT TOP(@__p_0) [t].[PKId], [t].[ArticleId], [t].[Message]
      FROM [T_Comments] AS [t]
      INNER JOIN [T_Articles] AS [t0] ON [t].[ArticleId] = [t0].[PKId]
      WHERE [t0].[PKId] = CAST(3 AS bigint))  AS  V8645b78cde2c477e8412c2d2cd6d0b69 )
```
