### ISSUE TITLE
8.0是还不能用吗？

### ISSUE THREAD

**Issue by lmxin123** [yangzhongke/Zack.EFCore.Batch#126]
#region 程序集 Zack.EFCore.Batch.MySQL.Pomelo_NET8, Version=8.1.8.0, Culture=neutral, PublicKeyToken=null
// C:\Users\birdf\.nuget\packages\zack.efcore.batch.mysql.pomelo_net8\8.1.8\lib\net8.0\Zack.EFCore.Batch.MySQL.Pomelo_NET8.dll
// Decompiled with ICSharpCode.Decompiler 8.1.1.7464
#endregion

using Zack.EFCore.Batch_NET7;

namespace Microsoft.EntityFrameworkCore;

public static class DbContextOptionsBuilderExtension_MySQLPomelo
{
    public static DbContextOptionsBuilder UseBatchEF_MySQLPomelo(this DbContextOptionsBuilder optBuilder)
    {
        throw ExceptionHelpers.CreateBatchNotSupportException_InEF7();
    }
}

**Comment by yangzhongke** [comment]
https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/README_CN_NET7.md

**Comment by lmxin123** [comment]
> https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/README_CN_NET7.md

这个链接说明我看了，我就是要用插入功能。我的疑问是efcore8项目为什么命名空间还是using Zack.EFCore.Batch_NET7;
调用UseBatchEF_MySQLPomelo();注册时，使用Add-Migration迁移命令报错了。
然后查看引用直接导航到以下方法了：
public static DbContextOptionsBuilder UseBatchEF_MySQLPomelo(this DbContextOptionsBuilder optBuilder)
{
    throw ExceptionHelpers.CreateBatchNotSupportException_InEF7();
}

是我哪里引用不对吗？

**Comment by yangzhongke** [comment]
只用插入功能的话，不用调用UseBatchEF_MySQLPomelo
