### ISSUE TITLE
能否提供一个接收实体列表参数的批量更新方法BulkUpdate？

### ISSUE THREAD

**Issue by MayGodBlessYouAMen** [yangzhongke/Zack.EFCore.Batch#127]
类似于下面的:

for (int i = 0; i < books.Count(); i++)
{
	books[i].UpdateTime = DateTime.Now();
}
using (TestDbContext ctx = new TestDbContext())
{
	ctx.BulkUpdate(books);
}

**Comment by MayGodBlessYouAMen** [comment]
另外，希望能将.net8版本中的EntityFrameworkCore版本升级到最新的8.0.2
非常感谢

**Comment by yangzhongke** [comment]
抱歉，无法支持这种写法。
虽然说库依赖的EFCore的版本是8.0.0，但是你可以单独安装对应的EFCore库到更高爸爸嫩。
