### ISSUE TITLE
批量修改和删除是否能支持实体集合?

### ISSUE THREAD

**Issue by l2999019** [yangzhongke/Zack.EFCore.Batch#128]
批量修改和删除是否能支持实体集合?
比如 类似下面这样
dbContext.BulkUpdateAsync(entities.ToList(), cancellationToken: cancellationToken);
dbContext.BulkDeleteAsync(entities.ToList(), cancellationToken: cancellationToken);

**Comment by yangzhongke** [comment]
抱歉，无法实现。
