### ISSUE TITLE
Is there a way to setup batching?

### ISSUE THREAD

**Issue by CliffCawley** [yangzhongke/Zack.EFCore.Batch#13]
For example with other libraries in the past I've used:

```
            var batchSize = 1000;
            await _context.MyTable
                .Where(x => x.Started < expireDate)
                .DeleteAsync(x => x.BatchSize = batchSize);
```

Is something like this possible? (So it will perform a delete in batches of 1000 at once, to ensure there aren't too many being deleted in a single call, causing a timeout)

**Comment by yangzhongke** [comment]
You can do it through Skip() and Take() [https://github.com/yangzhongke/Zack.EFCore.Batch/issues/12](https://github.com/yangzhongke/Zack.EFCore.Batch/issues/12)
