### ISSUE TITLE
希望能够支持第三方的Oracle Provider：Devart.Data.Oracle.EFCore

### ISSUE THREAD

**Issue by chukaif** [yangzhongke/Zack.EFCore.Batch#14]
目前Zack.EFCore.Batch支持的是Oracle的官方Provider，但是官方的Provider没有实现NetTopologySuite，难以操作空间/地理数据，希望能提供对Devart.Data.Oracle.EFCore的支持。

      使用前需要先安装dotConnect for Oracle，Devart为收费软件，不过可以试用或安装Express版，下载地址：https://www.devart.com/dotconnect/oracle/download.html

      参考文档：https://www.devart.com/entitydeveloper/docs/index.html?_ga=2.123315787.1509785132.1623132137-1510001402.1616997830

**Comment by yangzhongke** [comment]
抱歉，我看了一下，Devart.Data.Oracle.EFCore的核心的类都是internal的，无法扩展，因此无法对Devart.Data.Oracle.EFCore提供支持。

![image](https://user-images.githubusercontent.com/13821363/121453940-91206080-c9d4-11eb-854a-f5b4089f35da.png)

**Comment by yangzhongke** [comment]
你可以同时采用Oracle官方的Provider和Devart.Data.Oracle.EFCore，你日常的操作使用Devart的，批量操作的时候用官方的Provider
