### ISSUE TITLE
不支持AddDbContextPool吗

### ISSUE THREAD

**Issue by mushramb0** [yangzhongke/Zack.EFCore.Batch#15]
我用的是Zack.EFCore.Batch.MySQL.Pomelo包,在DbContext类的OnConfiguring方法中加上optionsBuilder.UseBatchEF_MySQLPomelo()后,
查询时报异常OnConfiguring' cannot be used to modify DbContextOptions when DbContext pooling is enabled.
请问怎么解决呢

**Comment by yangzhongke** [comment]
删掉OnConfiguring，把OnConfiguring中的代码都合并挪到AddDbContextPool中

**Comment by yangzhongke** [comment]
参考
[https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/Demo.MySQL.Pomelo/Program.cs](https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/Demo.MySQL.Pomelo/Program.cs)

**Comment by mushramb0** [comment]
可以了 3q

**Comment by mushramb0** [comment]
> 参考
> https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/Demo.MySQL.Pomelo/Program.cs

执行完DeleteRangeAsync再执行BulkInsertAsync报异常,System.InvalidOperationException: Cannot Open when State is Open.
哪里操作不对吗
await _applicationDbContext.DeleteRangeAsync<Goods>(x => x.date == date).ConfigureAwait(false);
await _applicationDbContext.BulkInsertAsync(list).ConfigureAwait(false);

**Comment by yangzhongke** [comment]
我代码的bug，我正在修复，稍等。

**Comment by yangzhongke** [comment]
已经修复，请更新到最新版。

**Comment by mushramb0** [comment]
> 已经修复，请更新到最新版。

这个问题好了 我又有个新问题 ,有个只读属性,是不需要更新到数据库的 ,但是用BulkInsertAsync的时候报异常,The property 'Goods.zk_final_price_d' could not be found. Ensure that the property exists and has been included in the model
这个应该怎么处理好

public string reserve_price { get; set; }
public decimal reserve_price_d => decimal.Parse(reserve_price);

**Comment by yangzhongke** [comment]
> 已经修复，请更新到最新版。

已经修复，请更新到最新版。

**Comment by yangzhongke** [comment]
已经修复，请更新到最新版。

**Comment by mushramb0** [comment]
> 已经修复，请更新到最新版。

可以了 谢谢
