### ISSUE TITLE
Mysql批量更新的时间只能精确到毫秒？

### ISSUE THREAD

**Issue by limengxina** [yangzhongke/Zack.EFCore.Batch#19]
预想结果：2021-06-24 17:29:13.408921
实际结果：2021-06-24 17:29:13.000000
生成的sql：Update `UserTs` SET `UpdateTime` = CURRENT_TIMESTAMP()

**Comment by yangzhongke** [comment]
我的库都是靠各个数据库的EF Core Provider来完成.net函数到数据库函数的翻译的。Pomelo的EF Core Provider就是把DateTime.Now翻译成CURRENT_TIMESTAMP()，所以我不方便做特殊处理。可以用mysql函数NOW(6)来获得6位精度的时间。
可以用ef core的[用户定义的函数映射](https://stackoverflow.com/questions/26299149/timestamp-with-a-millisecond-precision-how-to-save-them-in-mysql/26299379)特性来把Now(6)映射到一个自定义C#方法上，然后再在C#中用这个自定义方法代替DateTime.Now，这样SQL翻译就能变成调用NOW(6)了

**Comment by yangzhongke** [comment]
···
        public DateTime Now(int prec) => throw new NotSupportedException();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.HasDbFunction(typeof(PooledTestDbContext).GetMethod(nameof(PooledTestDbContext.Now), new[] { typeof(int) })).IsBuiltIn();
        }
···

···
await ctx.BatchUpdate<Book>()
.Set(b => b.PubTime, b => ctx.Now(6))
.Where(b => b.Id >3)
.ExecuteAsync();
···

**Comment by limengxina** [comment]
感谢解答,可以了
