### ISSUE TITLE
BulkInsert 可以配置更新部分字段吗？

### ISSUE THREAD

**Issue by XYCaptain** [yangzhongke/Zack.EFCore.Batch#20]
BulkInsert 好像不能处理自引用外键约束，是不是可以第二次只提交更新外键字段？

**Comment by yangzhongke** [comment]
BulkInsert 目前不处理关系操作，会忽略导航属性，请自行处理关联数据的先后插入关系。你可以为导航属性声明外键属性，然后为外键属性赋值。

**Comment by XYCaptain** [comment]
> BulkInsert 目前不处理关系操作，会忽略导航属性，请自行处理关联数据的先后插入关系。你可以为导航属性声明外键属性，然后为外键属性赋值。

您好 还有个小问题 主键自增的情况下 id设置了好像不生效

**Comment by yangzhongke** [comment]
自增主键的值是由数据库设定的，不能手动设置，这是数据库的机制决定的，我控制不了。

**Comment by yangzhongke** [comment]
你自己可以写代码，在插入数据库之前，调用DDL语句暂时先把自增停掉，然后插入，然后再启用自增。

**Comment by XYCaptain** [comment]
> 你自己可以写代码，在插入数据库之前，调用DDL语句暂时先把自增停掉，然后插入，然后再启用自增。

感谢您即时回复，EFCore在自增字段为非默认值的情况下采用用户输入值。
官方文档大概是这个意思：
“To override value generation with an explicit value, simply set the property to any value that is not the CLR default value for that property's type (null for string, 0 for int, Guid.Empty for Guid, etc.).。”
BulkInsert 有实现这样策略的可能性吗？

**Comment by XYCaptain** [comment]
> 你自己可以写代码，在插入数据库之前，调用DDL语句暂时先把自增停掉，然后插入，然后再启用自增。

Bulkinsert 我计划用在实时业务上，暂时停掉自增好像不是一个有效的方法。

**Comment by XYCaptain** [comment]
好吧，我做了些测试。自增和自定义ID同时存在不合理 ，感谢您的建议。

**Comment by yangzhongke** [comment]
Bulkinsert 在SQLServer底层的采用的SqlBulkCopy是支持你这个方式的。只要设定SqlBulkCopyOptions.KeepIdentity这个选项就行了，但是其他数据库是否支持还需要在调研。
不过这个选项目前在Bulkinsert 中没有开启，所以没法直接用。因为现在我在主干上在对代码做改动比较大的重构，所以暂时不方便立即帮你修改，你可以直接clone我这个项目的代码，然后直接把MSSQLBulkInsertExtensions.cs放到你的项目中，把BuildSqlBulkCopy这个方法的SqlBulkCopy bulkCopy = new SqlBulkCopy((SqlConnection)conn);改为
SqlBulkCopy bulkCopy = new SqlBulkCopy((SqlConnection)conn,SqlBulkCopyOptions.KeepIdentity);

等忙过了这阵子，如果我感觉可以把这个特性正式支持的话，我再改动正式支持，然后再通知你。

**Comment by XYCaptain** [comment]
> Bulkinsert 在SQLServer底层的采用的SqlBulkCopy是支持你这个方式的。只要设定SqlBulkCopyOptions.KeepIdentity这个选项就行了，但是其他数据库是否支持还需要再调研。
> 不过这个选项目前在Bulkinsert 中没有开启，所以没法直接用。因为现在我在主干上在对代码做改动比较大的重构，所以暂时不方便立即帮你修改，你可以直接clone我这个项目的代码，然后直接把MSSQLBulkInsertExtensions.cs放到你的项目中，把BuildSqlBulkCopy这个方法的SqlBulkCopy bulkCopy = new SqlBulkCopy((SqlConnection)conn);改为
> SqlBulkCopy bulkCopy = new SqlBulkCopy((SqlConnection)conn,SqlBulkCopyOptions.KeepIdentity);
> 
> 等忙过了这阵子，如果我感觉可以把这个特性正式支持的话，我再改动正式支持，然后再通知你。

感谢，我正在使用的是mysql。
1）自增开启后mysql自身的id会更新到pk的最大值，可能会跟自己生成的id冲突，同时使用自己编写id和自增id混用的策略好像不可行。
2）当数据库里存在ID相同记录时，并没开启覆盖。
另外，我查看了 mysql 的load local infile 好像支持部分字段和覆盖部分字段。

如果可以的话，可以告诉我修改哪段代码，我可以抽时间修改一下。如果我觉得修改可以解决问题的话，再提交相关代码。

**Comment by yangzhongke** [comment]
是这个类：https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/Zack.EFCore.Batch.MySQL.Pomelo/MySQLBulkInsertExtensions.cs

这里，如果测试通过，欢迎提交PR。如果想及时交流你研究过程中的想法，也可以添加我的微信 yzk10241024，请备注好友理由。
