### ISSUE TITLE
The count of columns should be even.

### ISSUE THREAD

**Issue by 1293459546** [yangzhongke/Zack.EFCore.Batch#22]
![image](https://user-images.githubusercontent.com/31330792/124346789-61e7c280-dc13-11eb-8633-c0255ab9f309.png)

批量修改5个列表字段时，报错 The count of columns should be even.

**Comment by yangzhongke** [comment]
请把实体类以及配置代码传上来，还有你用的数据库是什么

**Comment by 1293459546** [comment]
> 请把实体类以及配置代码传上来，还有你用的数据库是什么

您好，很抱歉没描述清楚，数据库用的是mysql5.7的版本，更新的时候，5个一下列数据更新没问题，不知道为什么5个以上就报列数量必须为偶数的异常

**Comment by yangzhongke** [comment]
谢谢反馈。
这是EF Core翻译优化导致的bug。我的程序是把
```
.Set(b => b.PubTime, b => DateTime.Now)
.Set(b => b.UpdateTime, b => DateTime.Now)
```
翻译成.Select(b=>new object[] { b.PubTime,DateTime.Now,b.UpdateTime,DateTime.Now})
这样来让EFCore帮我翻译，到那时对于 DateTime.Now这样重复的列，EF core会自动优化掉一列。
我先琢磨一下有没有根本解决的方法。
你可以先用如下两种方法绕过：
1）把Set的第二个参数相同的列拆分到两个Update中，也就update两次，每次update不同的列
2）通过变通的运算，让重复的值的表达式不一样，比如换成如下的样子
···
.Set(b => b.PubTime, b => DateTime.Now)
.Set(b => b.UpdateTime, b => DateTime.Now.AddDays(0))
···

**Comment by 1293459546** [comment]
> 谢谢反馈。
> 这是EF Core翻译优化导致的bug。我的程序是把
> 
> ```cs
> .Set(b => b.PubTime, b => DateTime.Now)
> .Set(b => b.UpdateTime, b => DateTime.Now)
> ```
> 
> 翻译成.Select(b=>new object[] { b.PubTime,DateTime.Now,b.UpdateTime,DateTime.Now})
> 这样来让EFCore帮我翻译，但是对于 DateTime.Now这样重复的列，EF core会自动优化掉一列，变成了new object[] { b.PubTime,DateTime.Now,b.UpdateTime})。
> 我先琢磨一下有没有根本解决的方法。
> 你可以先用如下两种方法绕过：
> 1）把Set的第二个参数相同的列拆分到两个Update中，也就update两次，每次update不同的列
> 2）通过变通的运算，让重复的值的表达式不一样，比如换成如下的样子
> 
> ```cs
> .Set(b => b.PubTime, b => DateTime.Now)
> .Set(b => b.UpdateTime, b => DateTime.Now.AddDays(0))
> ```

好的， 谢谢您的解答

**Comment by mfcguin** [comment]
`  await ctx.BatchUpdate<Article>().Set(a => a.Title, a => a.Title.Substring(1)).ExecuteAsync(); `
发现使用SubString()只有一个参数的重载也会报这个"The count of columns should be even"错误

**Comment by yangzhongke** [comment]
> ` await ctx.BatchUpdate<Article>().Set(a => a.Title, a => a.Title.Substring(1)).ExecuteAsync();` 发现使用SubString()只有一个参数的重载也会报这个"The count of columns should be even"错误
谢谢反馈

**Comment by yangzhongke** [comment]
bug 已从根本上修复，不再需要绕过的方法。请更新到最新版。请反馈测试结果。谢谢。_
