### ISSUE TITLE
Mysql BulkInsert, 实体中有复杂类型字段时，插入失败

### ISSUE THREAD

**Issue by EmmaCCC** [yangzhongke/Zack.EFCore.Batch#23]
比如某个字段是List<string>类型，该字段已映射成Json约定存储，数据库中该字段类型为varchar类型，用ef插入时，会将该字段自动序列化为字符串，能保存到数据库，但是用db.BulkInsert 扩展方法，就会报错不支持，可能是内部只处理的简单类型的字段，复杂类型的没安模型的配置处理。
我估计其他数据库也会报错吧。

**Comment by yangzhongke** [comment]
请提供实体以及实体配置的代码。

**Comment by EmmaCCC** [comment]
![QQ截图20210713170450](https://user-images.githubusercontent.com/18719014/125424394-9ef0712a-4098-45b6-91b3-47690f54da97.png)
![QQ截图20210713170423](https://user-images.githubusercontent.com/18719014/125424402-5b20bd37-5ae4-4724-ae30-e016e16259fd.png)
![QQ截图20210713170611](https://user-images.githubusercontent.com/18719014/125424466-6453ec36-841a-44f6-a450-877d26923b7c.png)

**Comment by yangzhongke** [comment]
谢谢反馈，目前都是忽略导航属性，对于你这样设置的Conversion，我以后会考虑支持。

**Comment by EmmaCCC** [comment]
> 谢谢反馈，目前都是忽略导航属性，对于你这样设置的Conversion，我以后会考虑支持。

我这不是导航属性，主要是个想把这种复杂类型作为json字符串存到数据库，然后获取出来再变成强类型方便操作。因为毕竟关系数据库，想存个复杂类型只能这样了。

**Comment by yangzhongke** [comment]
目前对于非基本类型我目前都认为是导航属性。

**Comment by yangzhongke** [comment]
已添加对Value Converter的支持，请更新到最新版。

**Comment by EmmaCCC** [comment]
> 已添加对Value Converter的支持，请更新到最新版。

老师威武！

**Comment by yangzhongke** [comment]
请测试一下你使用是否有问题。请反馈测试结果。谢谢。

**Comment by EmmaCCC** [comment]
nuget上没有更新最新版本啊

**Comment by yangzhongke** [comment]
![image](https://user-images.githubusercontent.com/13821363/144378473-d6cb0e95-bd3f-4076-bbdf-03e50cdca2eb.png)
