### ISSUE TITLE
BulkInsert 返回 311 rows were copied to xxx but only 1 were inserted.

### ISSUE THREAD

**Issue by FeiCunXinTai** [yangzhongke/Zack.EFCore.Batch#24]
老师您好，
BulkInsert 方法一直报错，关于这个错误我有把您的源码下载下来跑，但是错误好像是 MySqlConnector 里抛出的。
这个项目里的Issues也有类似的情况，需要修改链接字符串UseAffectedRows=true 但是还是报错。。。
实在是没办法了，最后还是只能在老师您这提个Issues

**Comment by FeiCunXinTai** [comment]
services.AddDbContextPool<ProjectContext>(options =>
            {
                options.UseMySql(Configuration.GetConnectionString("Edc_Project_DB"),
                           new MySqlServerVersion(new Version(8, 0, 23)),option=>
                           {
                               option.MaxBatchSize( 1000);
                               option.SchemaBehavior(Pomelo.EntityFrameworkCore.MySql.Infrastructure.MySqlSchemaBehavior.Ignore);
                           })
                       .EnableSensitiveDataLogging()
                       .EnableDetailedErrors();
                options.UseBatchEF_MySQLPomelo();
            })

**Comment by FeiCunXinTai** [comment]
SERVER=localhost;DATABASE=edc_project_db;USER=sa;PASSWORD=XXX;AllowLoadLocalInfile=true;

**Comment by yangzhongke** [comment]
请提供：
1）实体类代码
2）实体类的配置代码
3）可重现的插入数据的代码。

**Comment by FeiCunXinTai** [comment]
可以重现了，利用老师的Demo.MySQL.Pomelo，
/// <summary>
    /// 基础属性
    /// </summary>
    [Index(nameof(Id), IsUnique = true)]
    public abstract class BaseEntity
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        [Column("id", TypeName = "char(36)")]
        public Guid? Id { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("create_time", TypeName = "datetime(6)")]
        [Comment("创建时间")]
        public DateTime? Create_Time { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [MaxLength(200)]
        [Column("create_user")]
        [Comment("创建者")]
        public string Create_User { get; set; }

        /// <summary>
        /// 更新时间
        /// </summary>
        [Column("update_time", TypeName = "datetime(6)")]
        [Comment("更新时间")]
        public DateTime? Update_Time { get; set; }

        /// <summary>
        /// 更新人
        /// </summary>
        [MaxLength(200)]
        [Column("update_user")]
        [Comment("更新者")]
        public string Update_User { get; set; }

        /// <summary>
        /// 版本号
        /// </summary>
        [Timestamp]
        [Column("row_rersion", TypeName = "timestamp(6)")]
        [Comment("行版本号")]
        public DateTime? Row_Rersion { get; set; }

        /// <summary>
        /// 是否软删除
        /// </summary>
        [Column("is_soft_deleted")]
        [Comment("是否软删除")]
        public bool Is_Soft_Deleted { get; set; }
    }
    [Table("T_Books")]
    public class Book : BaseEntity, IAvailable
    {
        public Guid? Title { get; set; }
        public DateTime? PubTime { get; set; }
        public double Price { get; set; }
        public string AuthorName { get; set; }
        public int? Pages { get; set; }
        /// <summary>
        /// 访视是否激活可见
        /// </summary>
        public bool? Available { get; set; }
    }
static void Main(string[] args)
        {
            ServiceCollection services = new ServiceCollection();
            services.AddDbContextPool<ProjectContext>(optionsBuilder =>
            {
                optionsBuilder.LogTo(Console.WriteLine);
                string connStr = "server=localhost;user=sa;password=Abc12345;database=t0004;AllowLoadLocalInfile=true";
                optionsBuilder.UseMySql(connStr, new MySqlServerVersion(new Version(8, 0, 23)), builder =>
                {
                    builder.SchemaBehavior(MySqlSchemaBehavior.Ignore);
                });
                optionsBuilder.UseBatchEF_MySQLPomelo();
            });
            using (var sp = services.BuildServiceProvider())
            using (var ctx = sp.GetService<ProjectContext>())
            {
                List<Book> books = new List<Book>();
                for (int i = 0; i < 1000; i++)
                {
                    books.Add(new Book { AuthorName = "abc" + i, Price = new Random().NextDouble(), Title = Guid.NewGuid() ,Id=Guid.NewGuid(), Is_Soft_Deleted=false, Available = false });
                }
                ctx.BulkInsert(books);
            }
        }

**Comment by FeiCunXinTai** [comment]
只要加了index 或者设置成主键，就会抛出标题里的异常

**Comment by yangzhongke** [comment]
怎么没有给Id属性赋值呀。给Id属性赋值试试。

**Comment by yangzhongke** [comment]
收到了，我明天看一下。

**Comment by yangzhongke** [comment]
已修复，请更新到最新版

**Comment by FeiCunXinTai** [comment]
好的，谢谢老师
