### ISSUE TITLE
希望支持NET6

### ISSUE THREAD

**Issue by Coflys** [yangzhongke/Zack.EFCore.Batch#29]

**Comment by yangzhongke** [comment]
谢谢，已经迁移完成，基本测试完成。
https://www.nuget.org/packages/Zack.EFCore.Batch.MSSQL_NET6/

https://www.nuget.org/packages/Zack.EFCore.Batch.MySQL.Pomelo_NET6/

https://www.nuget.org/packages/Zack.EFCore.Batch.Npgsql_NET6/

https://www.nuget.org/packages/Zack.EFCore.Batch.Sqlite_NET6/

**Comment by Coflys** [comment]
谢谢！
