### ISSUE TITLE
Some services are not able to be constructed 

### ISSUE THREAD

**Issue by 18038268954** [yangzhongke/Zack.EFCore.Batch#31]
应该是我使用上的问题，不知道哪位大佬能回复一下。非常感激opt.UseBatchEF_MSSQL(); // EF批量组件

加上这句话直接pao抛异常了
![image](https://user-images.githubusercontent.com/56746295/133571529-16ae9c16-978e-4dc4-8d19-48f6b23e0e34.png)

**Comment by yangzhongke** [comment]
你用的是ef core的什么版本？.NET是什么版本，代码亮出来

**Comment by 18038268954** [comment]
抱歉了大哥，用了第三方框架的问题，我有个地方写错了。哈哈不知道为什么，我一发问题马上就能自己解决掉。刚才这个位置写错了。   EFCore.SqlServer5.0.1 .NET5
![image](https://user-images.githubusercontent.com/56746295/133572643-f42320f5-9567-4d38-b719-917a197b68a3.png)
