### ISSUE TITLE
批量更新时，某些字段未更新

### ISSUE THREAD

**Issue by chukaif** [yangzhongke/Zack.EFCore.Batch#32]
`var now = DateTime.Now;`
`var _48 = now.AddHours(-48);`
`var effect = await _dbContext.BatchUpdate<T_Evaluation>()`
`    .Set(a => a.Attitude, b => 5)`
`    .Set(a => a.Speed, b => 5)`
`    .Set(a => a.Specialized, b => 5)`
`    .Set(a => a.Note, b => "默认好评！")`
`    .Set(a => a.ModificationTime, b => now)`
`    .Where(a => !a.Attitude.HasValue && a.CreationTime.Value < _48)`
`    .ExecuteAsync();`

以上Attitude、Speed、Specialized三个字段均为记录打分的数字类型(int)
执行之后只有Attitude以及后面的Note、ModificationTime被更新
Speed和Specialized未更新，调换三个字段的顺序发现每次都只有第一个数字被更新。

用的包是：Zack.EFCore.Batch.MSSQL

**Comment by yangzhongke** [comment]
这是一个已知缺陷，解决方式详见
[https://github.com/yangzhongke/Zack.EFCore.Batch/issues/22#issuecomment-873737252](https://github.com/yangzhongke/Zack.EFCore.Batch/issues/22#issuecomment-873737252)
