### ISSUE TITLE
批量删除及更新用于工作单元的问题

### ISSUE THREAD

**Issue by fen617193145** [yangzhongke/Zack.EFCore.Batch#33]
好像批量删除及更新都是内部直接savechanges了，那么在工作单元中该怎么使用呢？

**Comment by yangzhongke** [comment]
我这个就是用来解决ef core批量操作性能瓶颈用的。
如果你的批量操作不构成性能平静，你就还继续用ef core的删除、更新机制就行了。
DDD有局限性，所以不需要什么地方都恪守DDD的原则。需要开发者在性能和DDD原则之间做出妥协。
