### ISSUE TITLE
Sign your assemblies please 

### ISSUE THREAD

**Issue by stefc** [yangzhongke/Zack.EFCore.Batch#34]
We can't use your packages until they are signed

**Comment by yangzhongke** [comment]
Signed assembly is mainly used for .Net Framework , and "For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding". Therefore, I will not publish the signed version.
If you need a signed version, you can pull the source code and compile them by yourself.
'
