### ISSUE TITLE
BulkInsertAsync无法正确插入正确的对象主键

### ISSUE THREAD

**Issue by BeanTang** [yangzhongke/Zack.EFCore.Batch#36]
数据库:Postgresql
我写的测试代码是想插入Int32.MinValue →  Int32.MinValue + 1000*1000 的主键范围.
但我测试得到的结果是 BulkInsertAsync 会使用自增的模式.

用Efcore自身的AddRangeAsync是正常的.

**Comment by yangzhongke** [comment]
抱歉，我研究的结果是，Postgresql的COPY实现的批量不支持显式指定id的值。如果您有不同的研究结果，欢迎提供。
