### ISSUE TITLE
BatchUpdateBuilder<TEntity> Set<TP>  如何定义参数作为集合传

### ISSUE THREAD

**Issue by girvs** [yangzhongke/Zack.EFCore.Batch#38]
public virtual Task UpdateRangeAsync(
            Expression<Func<TEntity, bool>> predicate,
            params KeyValuePair<Expression<Func<TEntity>>, Expression<Func<TEntity>>>[] fieldValue
        )
        {
            if (!fieldValue.Any()) return Task.CompletedTask;
            var where = predicate.And(OtherQueryCondition);
            var obj = DbContext.BatchUpdate<TEntity>().Where(where);
            foreach (var keyValuePair in fieldValue)
            {
                obj.Set(keyValuePair.Key, keyValuePair.Value);
            }

            return obj.ExecuteAsync();
        }

如上所示：当需要更新多个字段，多个字段的修改的表达式以集合的方式传过来？

谢谢！

**Comment by yangzhongke** [comment]
谢谢反馈，忙过了下周，我会看一下。

**Comment by yangzhongke** [comment]
请问你想要什么样的调用效果，请提供一个例子。

**Comment by girvs** [comment]
感谢！

   
 public BatchUpdateBuilder<TEntity> Set<TP>(
      Expression<Func<TEntity, TP>> name,
      Expression<Func<TEntity, TP>> value)
    {
      string name1 = (name.Body as MemberExpression).Member.Name;
      this.setters.Add(new Setter<TEntity>()
      {
        Name = (LambdaExpression) name,
        Value = (LambdaExpression) value,
        PropertyType = typeof (TP),
        PropertyName = name1
      });
      return this;
    }

在上述设置字段的值的时候，指定了TP的，传递参数只能单一的参数传递，不能进行批量传参，所以看能添加或者修改以更新的字段以集合的方式进行传参  如Dictionary<string, object>类型，key为属性名，value为属性对应的值，如下所示：

        public Task UpdateRange(Expression<Func<TEntity, bool>> predicate, IDictionary<string, object> updatefileds)
        {
            var bub = DbContext.BatchUpdate<TEntity>().Where(predicate);
            foreach (var updatefiled in updatefileds)
            {
                bub.Set(updatefiled.Key, updatefiled.Value);
            }

            return bub.ExecuteAsync();
        }

或者其它集合方式

**Comment by yangzhongke** [comment]
谢谢。
我是不是提供了一个使用非Expression类型参数的Set方法就可以满足您的要求了？
比如
```
public BatchUpdateBuilder Set(string name,object value)
```

**Comment by girvs** [comment]
是的

**Comment by yangzhongke** [comment]
完成了。请更新到最新版。用法：
```
await ctx.BatchUpdate<Book>()
.Set("Title", "Haha")
.Set("Price", 3.14)
.Where(b => b.Price > 888)
.ExecuteAsync();
```

**Comment by girvs** [comment]
谢谢
