### ISSUE TITLE
Mysql库代码中对json类型的字段进行HasConversion（）后，BulkInsert()方法无法使用

### ISSUE THREAD

**Issue by zzy092** [yangzhongke/Zack.EFCore.Batch#41]
![jsonClass](https://user-images.githubusercontent.com/74536128/142745751-38db8a16-f38b-4e67-b660-d77570c7df2c.png)
![ExtJson](https://user-images.githubusercontent.com/74536128/142745772-b6b835c2-a7a4-4cc3-bd3e-5df9543fe6dc.png)
![jsonConfig](https://user-images.githubusercontent.com/74536128/142745756-049ffe39-a1bf-45f8-8d27-a3eb7779863b.png)

异常信息：NotSupportedException: Type List`1 not currently supported. Value: System.Collections.Generic.List`1

**Comment by yangzhongke** [comment]
已添加对Value Converter的支持，请更新到最新版。

**Comment by yangzhongke** [comment]
请反馈测试结果，谢谢。
