### ISSUE TITLE
Oracle中使用 BulkInsert() 会乱码，乱码的字段中有的涉及有汉字有的没有涉及汉字

### ISSUE THREAD

**Issue by zzy092** [yangzhongke/Zack.EFCore.Batch#42]
![乱码](https://user-images.githubusercontent.com/74536128/142745891-97ff6bac-10f9-49a2-a91f-808d116202ca.png)

**Comment by zzy092** [comment]
在用 EFCore 的Add方法 没有遇到会乱码的情况，而且在我第一次运行的时候，不小心点了两次，插入之前我没有校验主键与唯一索引，结果这两份数据都插进去了，使得主键冲突了，出现了两个相同的主键，之后这张表只能查不能对其进行增删改，查看表的状态，两个索引的状态为失效状态，当时代码报的错为下图
![未命名图片](https://user-images.githubusercontent.com/74536128/142746309-0602ee15-fb46-411b-b4ae-765dd89e2bd5.png)

**Comment by yangzhongke** [comment]
请提供可重现问题的代码，也就是我直接拿过来可以重现问题的代码。

**Comment by yangzhongke** [comment]
我没法重现这个问题，不过我改了一个可能和这个相关的一些代码，也许能解决问题，请测试一下。如果测试成功，请回复。

**Comment by zzy092** [comment]
没有解决，简单说下落地流程，我写了一个造数据落地的类，该类定义了一个listData属性，该类在new的时候会自动生成本次落地数据，然后在Program的main方法中 先用ef自己的add，一次性saveChange，落到库里是没有乱码的，然后同一个listData 用在老师的方法里落地还是乱码，我把相关代码和数据库设计贴在下面 
![Uploading 0431BA67-A275-4448-B14C-8F0B48C3090D.jpeg…]()

**Comment by zzy092** [comment]
![035D39A9-9DDD-400B-88E6-1B57466C5057](https://user-images.githubusercontent.com/74536128/144380926-f1ae397a-db1a-4b21-87f1-f0cb81aec023.jpeg)
![A1FAFCD4-54DE-4FF4-B2EA-72420823550A](https://user-images.githubusercontent.com/74536128/144380942-b01fa13d-531d-4738-9f85-c659eacd9966.jpeg)
![A24B7A6C-702A-44FD-B119-3A43E702E4DD](https://user-images.githubusercontent.com/74536128/144380963-2614576c-b9de-4633-87b3-aeccbf2d85ca.jpeg)
![4F503118-1F23-4C3E-98EF-9FE7568DDAAE](https://user-images.githubusercontent.com/74536128/144380990-a27ab95e-cf06-4852-9a01-20e877b8fdae.jpeg)
![60D918CE-CF5E-41B6-96E4-21A2BA288AB6](https://user-images.githubusercontent.com/74536128/144381011-f1197ed7-0aae-45b1-8f52-8d98b968fa89.jpeg)

**Comment by yangzhongke** [comment]
你看看你自己直接用OracleBulkCopy做数据插入会乱码吗？因为我的方法也只是对OracleBulkCopy的简单封装而已。
