### ISSUE TITLE
解决Value Converter的支持异常

### ISSUE THREAD

**Issue by zzy092** [yangzhongke/Zack.EFCore.Batch#45]
我下载最新的 Zack.EFCore.Batch.MySql.Pomelo(1.5.1)
在断点还没有走到BulkInsert时，之前的批量删除方法报错了，而且我用ef的Add也会报相同的错误 ，之前除了批量数据落地功能外，修改跟删除是可以用的，而且也不会影响现有ef的增删改，本次更新的包按要求都升到了net 5.0
![DAC9A2D7-B916-427B-A745-63A21246B0E9](https://user-images.githubusercontent.com/74536128/144383268-5c642da8-7b91-4242-aafd-9bbe1b99a5de.png)
![Uploading BB3F8C34-D8E5-4A5A-A867-04D9AECF6BC9.jpeg…]()

**Comment by zzy092** [comment]
![Uploading F862F9B8-99C9-4F1A-9F2A-405A079E33B9.jpeg…]()

**Comment by zzy092** [comment]
Unable to resolve service for type 'Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlSqlExpressionFactory' while attempting to activate 'Zack.EFCore.Batch.MySQL.Pomelo.Internal.ZackQuerySqlGeneratorFactory_MySQLPomelo'.

**Comment by zzy092** [comment]
![Uploading 1182D611-8D6A-4FF1-83FD-26CCF0787032.jpeg…]()

**Comment by yangzhongke** [comment]
最新版是1.5.3

**Comment by yangzhongke** [comment]
请更新到最新版

**Comment by zzy092** [comment]
已解决 🙏
