### ISSUE TITLE
.net6 DeleteRange删除失败

### ISSUE THREAD

**Issue by chenjingchun** [yangzhongke/Zack.EFCore.Batch#46]
![图片](https://user-images.githubusercontent.com/4917940/145928457-79a5f4a2-f7eb-46f6-90b4-a82af37063b6.png)
zack.efcore.batch.npgsql_net6版本6.0.5
Npgsql数据库，Device中是设置了主键的
opt.UseBatchEF_Npgsql(); // EF批量组件

**Comment by yangzhongke** [comment]
请 见
[https://github.com/yangzhongke/Zack.EFCore.Batch/issues/17](https://github.com/yangzhongke/Zack.EFCore.Batch/issues/17)
