### ISSUE TITLE
更新时赋值有问题

### ISSUE THREAD

**Issue by chukaif** [yangzhongke/Zack.EFCore.Batch#47]
如下：
`.Set(a => a.ReadedAt, DateTime.Now)`
ReadAt 为 DateTime? 类型，给它赋一个DateTime类型的值时出现错误：
`Expression of type 'System.DateTime' cannot be used for return type 'System.Nullable`1[System.DateTime]'`

使用`.Set(a => a.ReadedAt, b=> DateTime.Now)` 这样的形式则没有问题。

**Comment by yangzhongke** [comment]
谢谢反馈

**Comment by yangzhongke** [comment]
bug已修复，请更新到最新版。
