### ISSUE TITLE
Skip and Take don't seem to work

### ISSUE THREAD

**Issue by roji** [yangzhongke/Zack.EFCore.Batch#48]
In your [docs](https://github.com/yangzhongke/Zack.EFCore.Batch#take-skip), you show a sample using Skip and Take in a bulk delete operation:

```c#
await ctx.Comments.Where(c => c.Article.Id == id).Skip(3).Take(10).DeleteRangeAsync<Comment>(ctx);
```

However, when executing this locally, I don't see any trace of the Skip and Take in the generated SQL:

```sql
Delete FROM [Blogs] WHERE [Id] > 3
```

What SQL where you thinking of generating for translating Skip/Take for DELETE? Also, since there's no OrderBy in your sample, the Skip/Take operators are non-deterministic.

<details>
<summary>Code sample</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

_ = await ctx.Blogs.Where(b => b.Id > 3).Skip(2).Take(3).DeleteRangeAsync(ctx);

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .UseBatchEF_MSSQL()
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>

**Comment by yangzhongke** [comment]
Thanks for your feedback. I'll check it.

**Comment by yangzhongke** [comment]
Bug fixed, please update the package to the lastest version.
As the first parameter DeleteRangeAsync is type of IQueryable, you can use OrderBy:
```
 await ctx.Comments.Where(c => c.Article.Id == 3).OrderBy(c => c.Message).Skip(5).Take(10)
                        .DeleteRangeAsync(ctx);
```

**Comment by roji** [comment]
Thanks. You may want to update your docs and remove the sample that has Skip/Take without OrderBy, as that's completely non-deterministic. Take without OrderBy can make sense if you want "any 10 rows", but Skip really is meaningless without OrderBy.

**Comment by yangzhongke** [comment]
Thanks for your advice.
