### ISSUE TITLE
支持下EFCore.Relation 6.0.1

### ISSUE THREAD

**Issue by shuaqq2004** [yangzhongke/Zack.EFCore.Batch#49]
如题
不然更新nuget冲突，其他包都支持6.0.1了

**Comment by yangzhongke** [comment]
![image](https://user-images.githubusercontent.com/13821363/147305514-7063d901-7f2a-46d9-aeec-71e7ec7c301a.png)
我这里不冲突呀，我设置的是>=6.0.0
所以6.0.1也是支持的
![image](https://user-images.githubusercontent.com/13821363/147305566-c2c208b0-ec13-4334-9307-96ca9e1a4249.png)

**Comment by shuaqq2004** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NU1107	Microsoft.EntityFrameworkCore.Relational 中检测到版本冲突。直接安装/引用 Microsoft.EntityFrameworkCore.Relational 6.0.1 到项目 Tengchong.Core 可解决此问题。 
 Tengchong.Core -> Npgsql.EntityFrameworkCore.PostgreSQL 6.0.2 -> Microsoft.EntityFrameworkCore.Relational (>= 6.0.1) 
 Tengchong.Core -> Zack.EFCore.Batch.Npgsql 1.5.8 -> Zack.EFCore.Batch 1.5.8 -> Microsoft.EntityFrameworkCore.Relational (>= 5.0.5 && < 6.0.0).	Tengchong.Core	D:\Project\Tengchong\src\Tengchong.Core\Tengchong.Core.csproj	1	

-----------------
Zack.EFCore.Batch.Npgsql

**Comment by yangzhongke** [comment]
请仔细阅读文档
![image](https://user-images.githubusercontent.com/13821363/147306018-ea1d08a8-810e-4473-b25c-50f8b45d9de9.png)

https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/README_CN.md
