### ISSUE TITLE
.net6 DeleteRange  BatchUpdate  失败

### ISSUE THREAD

**Issue by zhuoyue03007** [yangzhongke/Zack.EFCore.Batch#50]
如同此问题 [https://github.com/yangzhongke/Zack.EFCore.Batch/issues/46#issue-1079272716](url)

目前可以先通过设置ExecuteAsync、DeleteRangeAsync的ignoreQueryFilters: true参数，禁用QueryFilter，这样的方式绕过。如下：

var drowsdf = await context.BatchUpdate<PlatformOrderInfo>()
	.Where(x => x.PlatformOrderNo == platformOrderNo)
	.Set(x => x.State, x => 10)
	.ExecuteAsync(ignoreQueryFilters: true);
这样QueryFilter就会被忽略了，如果想继续使用对应的QueryFilter，可以手动把过滤条件写到Where条件中。我下周再研究从根本解决的办法。

await _sysMenuMenuDistributionRep.Context.DeleteRangeAsync<Sys_MenuDistribution>(u => u.TenantId.Equals(input.TenantId), ignoreQueryFilters: true);

**组件升级到 6.0.8 你这种写法也会报错（The given key '__ef_filter__p_0' was not present in the dictionary.） 
退回到6.0.6就不会**

**Comment by yangzhongke** [comment]
谢谢反馈，我这里搭建重现问题的步骤比较麻烦。你方便建一个可执行的、能重现这个问题的最简单的项目发给我吗？发到网盘，粘贴链接到这里就可以。

**Comment by yangzhongke** [comment]
问题长期未回复，暂时关闭，如果有进一步的信息提供，请重新打开issue
