### ISSUE TITLE
BulkInsertAsync 看不到生成的 sql 语句 (Mysql 数据库 .NET 5)

### ISSUE THREAD

**Issue by gaoconggit** [yangzhongke/Zack.EFCore.Batch#51]
BulkInsertAsync 看不到生成的 sql 语句 (Mysql 数据库 .NET 5)

**Comment by yangzhongke** [comment]
bulkinsert是通过MysqlBulkcopy实现的，不是通过传统的SQL语句。所以看不到是正常的，因为没有SQL。
