### ISSUE TITLE
BulkInsert options.InsertIfNotExists

### ISSUE THREAD

**Issue by xeleoss** [yangzhongke/Zack.EFCore.Batch#52]
It would be nice to add support for inserting objects only if they do not exist.
For example, entityframework-extensions it looks like this:
`context.BulkInsert(customers, options => {
    options.InsertIfNotExists = true;
});`

**Comment by yangzhongke** [comment]
Thanks for your feedback.
I use SqlBulkCopy/MysqlBulkCopy to implement BulkInsert, they are more performant than Insert SQL clause, however, they don't support InsertIfNotExists, so this library cannot support InsertIfNotExists either.
