### ISSUE TITLE
DeleteRangeAsync with predicate don't work in .Net6

### ISSUE THREAD

**Issue by begerard** [yangzhongke/Zack.EFCore.Batch#54]
Hi @yangzhongke,

I have an exception when I use DeleteRangeAsync with a predicate since my upgrade with the .Net6 package. Without predicate it works (empting the whole table).

My code:
await _context.DeleteRangeAsync<PlanningTask>(a => a.Date == date);

The exception:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

The callstack:
>    at Zack.EFCore.Batch.Internal.BatchUtils.BuildWhereSubQuery[TEntity](IQueryable1 queryable, DbContext dbCtx, String aliasSeparator)
>    at System.Linq.BatchEFExtensions.GenerateDeleteSQL[TEntity](DbContext ctx, IQueryable1 queryable, Expression1 predicate, Boolean ignoreQueryFilters, IReadOnlyDictionary2& parameters)
>    at System.Linq.BatchEFExtensions.<DeleteRangeAsync>d__11.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
>    ...

**Comment by begerard** [comment]
I should add that I use the npgsql version.

**Comment by yangzhongke** [comment]
Thanks for your feedback.
I cannot reproduce this issue, could you please provide with a standalone project which can reproduce it?
Thanks.

**Comment by begerard** [comment]
I tried to repro it with a simple case, and indeed it does work as intended. I'll try to extend my repro until I hit the problem I have in our software so you can reproduce locally.

**Comment by yangzhongke** [comment]
Thanks for your reply.
Although I did not reproduce the error, I found the possible cause of the error, I have fixed it, please use the latest version to try.  
If this issue is fixed, please let me know.

**Comment by begerard** [comment]
Hi,

I just tested it in our application and the 6.0.10 version solve my problem as you suspected.

Thanks for your help and kind support!
