### ISSUE TITLE
为什么我的pgsql 的DeleteRangeAsync 对应的sql是这样的

### ISSUE THREAD

**Issue by blackmaple** [yangzhongke/Zack.EFCore.Batch#55]
Zack.EFCore.Batch.Npgsql_NET6, Version=6.0.8.0

` this.Context.DeleteRangeAsync<T_E_Parameter_Config>(p => p.E_Resource == resourceName);

 Delete FROM schema_english.t_e_parameter_config WHERE sys_id IN(SELECT sys_id FROM (SELECT t.sys_id, t.e_code, t.e_resource, t.e_value, t.sys_create_time, t.sys_status
      FROM schema_english.t_e_parameter_config AS t
      WHERE t.e_resource = @__resourceName_0)  AS  Ve36d2e6ab0f3452e8fc7147e775e99d7 )`

**Comment by blackmaple** [comment]
Zack.EFCore.Batch.Npgsql_NET6, Version=6.0.8.0 异常
降级到6.0.6.0就好了

**Comment by yangzhongke** [comment]
之前生成的sql对于复杂的sql支持有问题，所以新版本改成子查询了。运行没问题吧？
