### ISSUE TITLE
可否新增一些配置参数?

### ISSUE THREAD

**Issue by gaoconggit** [yangzhongke/Zack.EFCore.Batch#58]
await DbContext.BulkInsertAsync(list, m =>
                {
                    m.PreserveInsertOrder = false;
                    m.BatchSize = 5000;
                    m.PropertiesToExclude = new List<string>() { "CreateDatetime" };
                });

**Comment by yangzhongke** [comment]
PreserveInsertOrder  这个参数的意义是什么呢？我按照list中的顺序给到SqlBulkCopy有什么问题？
