### ISSUE TITLE
新年快乐，请问能否支持【达梦数据库】，谢谢！

### ISSUE THREAD

**Issue by 13408381254** [yangzhongke/Zack.EFCore.Batch#59]
您好，新年快乐，请问能否支持【达梦数据库】，谢谢！
达梦数据库地址：https://www.dameng.com/list_17.html#pro1

**Comment by yangzhongke** [comment]
我这个库是基于对应的数据库的EF core 5/6 的Provider，达梦有EF Core 5/6 的Provider吗？

**Comment by 13408381254** [comment]
感谢您的回复，我晚上安装最新版 达梦 数据库确定后，给您回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月25日(星期二) 下午5:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangzhongke/Zack.EFCore.Batch] 新年快乐，请问能否支持【达梦数据库】，谢谢！ (Issue #59)





 
我这个库是基于对应的数据库的EF core 5/6 的Provider，达梦有EF Core 5/6 的Provider吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 13408381254** [comment]
您好，查询官方文档，目前支持EF 6、EF Core。







------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月25日(星期二) 下午5:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangzhongke/Zack.EFCore.Batch] 新年快乐，请问能否支持【达梦数据库】，谢谢！ (Issue #59)





 
我这个库是基于对应的数据库的EF core 5/6 的Provider，达梦有EF Core 5/6 的Provider吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangzhongke** [comment]
文档在哪里？支持EF Core的Nuget包名是什么？

**Comment by 13408381254** [comment]
由于邮件大小限制，文档无法直接发送给您，非常抱歉。
请您打开网页下载，谢谢。
文档地址：https://www.dameng.com/list_103.html
文档名称：DM8程序员手册.pdf
程序包需要安装达梦数据库后，在安装文件夹中才能找到。

------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yangzhongke/Zack.EFCore.Batch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月25日(星期二) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangzhongke/Zack.EFCore.Batch] 新年快乐，请问能否支持【达梦数据库】，谢谢！ (Issue #59)





 
文档在哪里？支持EF Core的Nuget包名是什么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangzhongke** [comment]
找到了，谢谢。目前看来，这个包支持EF Core 5.0.1，初步调研是可以支持在.net5的版本中支持。我会尝试支持达梦数据库。
如果方便话，请你加我微信yzk10241024，因为我对达梦数据库不熟悉，可能需要你帮忙做测试谢谢。

**Comment by 13408381254** [comment]
好的，非常感谢。
我稍后微信加您。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月25日(星期二) 晚上9:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangzhongke/Zack.EFCore.Batch] 新年快乐，请问能否支持【达梦数据库】，谢谢！ (Issue #59)





 
找到了，谢谢。目前看来，这个包支持EF Core 5.0.1，初步调研是可以支持在.net5的版本中支持。我会尝试支持达梦数据库。
 如果方便话，请你加我微信yzk10241024，因为我对达梦数据库不熟悉，可能需要你帮忙做测试谢谢。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangzhongke** [comment]
已经发布对.NET 5的支持。由于达梦还没有发布.NET 6的EF Core Provider，所以暂时只支持EF Core 5。

Install-Package ZackEFCore.Batch.Dm

optionsBuilder.UseBatchEF_DM();
