### ISSUE TITLE
可否支援 InMemory

### ISSUE THREAD

**Issue by raychiutw** [yangzhongke/Zack.EFCore.Batch#60]
UnitTest 中會用 InMemory 替換 MSSQL,
套件可否增加對 InMemory 的支持

**Comment by yangzhongke** [comment]
谢谢建议，我会尝试对inmem提供支持

**Comment by yangzhongke** [comment]
已经完成对InMemory的支持。
对于.NET 5用户：Install-Package Zack.EFCore.Batch.InMemory
对于.NET 6用户: Install-Package Zack.EFCore.Batch.InMemory_NET6

Install-Package Zack.EFCore.Batch.InMemory_NET6

请测试、反馈。
