### ISSUE TITLE
oracle 中怎么传递事务？

### ISSUE THREAD

**Issue by githubzsy** [yangzhongke/Zack.EFCore.Batch#61]
```C#
// 开启EF原生的事务
using(var tran = await _equipmentGroupManagerRepository.BeginTransactionAsync())
{
    // 实际就是DeleteRange方法
    var i =_equipmentGroupManagerRepository.Delete(a=>a.EquipmentGroupId == dto.EquipmentGroupId && a.Level==dto.Level);

    // 实际就是BulkInsert方法
    _equipmentGroupManagerRepository.BulkInsert(managers);

    tran.Commit();
}
```
如上图所示，代码逻辑就是先删除再插入，都是调用的Batch中的方法，但是删除操作成功了，到新增时报出了以下错误：
```
Oracle.ManagedDataAccess.Client.OracleException:“ORA-26085: 直接路径操作必须启动它自己的事务处理”
```
是事务传递的问题吗?

另外不知道哪里有API文档可以参考啊？

**Comment by yangzhongke** [comment]
BulkInsert有一个OracleBulkCopyOptions参数，具体说明https://docs.oracle.com/cd/E11882_01/win.112/e23174/OracleBulkCopyOptionsEnumeration.htm#ODPNT7690

**Comment by githubzsy** [comment]
如果修改成 
```c#
Context.BulkInsert(entities,Oracle.ManagedDataAccess.Client.OracleBulkCopyOptions.UseInternalTransaction);
```
又会报出下面错误了，大意应该是已经开启了一个事务？
System.InvalidOperationException:“Connection is already part of a local or a distributed transaction”

**Comment by githubzsy** [comment]
另外查询了一些资料，发现 OraclBulkInsert 是个危险操作，如果插入数据主键重复的话会导致表结构会破坏。
https://www.modb.pro/db/23553
还有资料说这个操作本身就不支持事务。
另外我自己测试了一下，的确插入重复主键会导致表出现问题。

**Comment by yangzhongke** [comment]
谢谢反馈，这是OracleBulkCopy的缺陷，我只是基于它做的封装，所以我也无法解决，您可以把bug反馈给oracle。
