### ISSUE TITLE
实体的最后一个字段是 bool 时，myql 数据库中为 bit 

### ISSUE THREAD

**Issue by gaoconggit** [yangzhongke/Zack.EFCore.Batch#62]
批量插入 bool 类型始终为 1
插入 false 也是 1

**Comment by yangzhongke** [comment]
只有是最后一个字段才会这样？

**Comment by gaoconggit** [comment]
> 只有是最后一个字段才会这样？

是的

**Comment by gaoconggit** [comment]
![image](https://user-images.githubusercontent.com/10905068/160345057-d419befa-5ca5-4434-9bc5-24734cd45193.png)
![image](https://user-images.githubusercontent.com/10905068/160345139-1f219280-a1ab-48cd-9825-e2cc744fcae9.png)

**Comment by gaoconggit** [comment]
数据库类型改为 tinyint(1) 可以修复这个 bug

**Comment by yangzhongke** [comment]
谢谢反馈，我有时间的时候看看是我代码的问题还是mysqlbulkcopy的问题

**Comment by yangzhongke** [comment]
我测试了一下，这是mysqlbulkcopy的问题，不是我代码的问题。
