### ISSUE TITLE
更新操作，可以添加表达式树写法支持么？避免一次次的set

### ISSUE THREAD

**Issue by ByZhouhang** [yangzhongke/Zack.EFCore.Batch#66]
参数传递方式：   Expression<Func<TEntity, TEntity>> updateFactory

x   => new Entity
                {
                    Sort = 2,
                   Name="XXXX
                }

**Comment by yangzhongke** [comment]
谢谢建议，目前的功能够用了。EF Core 7也计划出类似的功能，所以我也就不准备增加新功能了。

**Comment by ByZhouhang** [comment]
> 谢谢建议，目前的功能够用了。EF Core 7也计划出类似的功能，所以我也就不准备增加新功能了。

我想在您库的基础上本地增加这种写法的支持，但是发现有点问题，不知道是不是我的操作有问题？
 var builder = _dbContext.BatchUpdate<TEntity>();

            Func<TEntity, TEntity> func = updateFactory.Compile();

            List<PropertyInfo> list = ((MemberInitExpression)updateFactory.Body).Bindings.Select<MemberBinding, string>((Func<MemberBinding, string>)(_param1 => _param1.Member.Name)).Select<string, PropertyInfo>((Func<string, PropertyInfo>)(_param1 => (PropertyInfo)typeof(TEntity).GetProperty(_param1, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))).ToList<PropertyInfo>();

            TEntity applyObj = func(new TEntity());

            foreach (PropertyInfo prop in list)
            {
                var propName = prop.Name;
                var value = prop.GetValue((object)applyObj);

                builder.Set(propName,   value);
            }
            return await builder.Where(where).ExecuteAsync()>0;

**Comment by yangzhongke** [comment]
抱歉，比较忙，您先自己调吧，不好意思。

**Comment by yangzhongke** [comment]
我想到一个思路。
这个库支持这种写法
Set("Message","abc")

所以你可以用反射的方式获取对象的所有属性，然后循环调用Set来实现。

**Comment by ByZhouhang** [comment]
> 我想到一个思路。 这个库支持这种写法 Set("Message","abc")
> 
> 所以你可以用反射的方式获取对象的所有属性，然后循环调用Set来实现。

我就是用这个思路做的，当guid？  属性 设置null的时候，会出问题，有具体值的没问题，库这种Set("Message","abc")  不支持Set("Message",null)

**Comment by yangzhongke** [comment]
"Set("Message","abc") 不支持Set("Message",null)"这个bug已经修复
请更新到最新版。
