### ISSUE TITLE
BatchUpdate时，多个Set的属性为枚举类型时，更新的数据不对

### ISSUE THREAD

**Issue by FeiCunXinTai** [yangzhongke/Zack.EFCore.Batch#69]
--下面是更新的代码   
await uow.DbContext.BatchUpdate<Item_Data_Status>().Set(q => q.Status, q => DataStatus.ESigned).Set(q => q.ESign_Status, q => ESignStatus.ESigned).Where(q => q.Subject == form.Subject && q.Form_Status_ID == form.Id.Value).ExecuteAsync();

--下面是字段的属性
  /// <summary>
        /// 表单状态
        /// </summary>
        [Column("status", TypeName = "smallint")]
        [Comment("表单状态")]
        public DataStatus Status { get; set; }
  /// <summary>
        /// 电子签名状态
        /// </summary>
        [Column("esign_status", TypeName = "smallint")]
        [Comment("电子签名状态")]
        public ESignStatus ESign_Status { get; set; }

DataStatus.ESigned ==4
ESignStatus.ESigned==3

更新到数据库的时候都变成了4。
没找到生成的SQL，所以没贴上来。
请大佬帮忙看看，很多生产数据都出错了。。。

**Comment by yangzhongke** [comment]
请提供一个可执行的、能重现这个问题的最简单的项目。发到网盘，粘贴链接到这里就可以。

**Comment by FeiCunXinTai** [comment]
await uow.DbContext.BatchUpdate<Item_Data_Status>().Set(q => q.Status, q => DataStatus.ESign).Set(q => q.ESign_Status, q => ESignStatus.ESigned).Where(q => q.Subject == form.Subject && q.Form_Status_ID == form.Id.Value).ExecuteAsync();

我把上面两个枚举的属性名改了，就没问题了。
改成了DataStatus.ESign 与  ESignStatus.ESigned

**Comment by xtxk110** [comment]
我原来也遇到过，把枚举名称改成不一样的。就对了

**Comment by FeiCunXinTai** [comment]
大佬，这个问题的代码量太多了，不太好弄出来，而且似乎是在class中设置了属性的默认值，然后在迁移文件中又设置了默认值。
似乎是这种场景导致的。
这个issue没有准备好测试用例，实在抱歉

**Comment by yangzhongke** [comment]
谢谢反馈，这是一个已知问题，目前没有想到解决的方法。就用你的方法绕过去吧。

**Comment by yangzhongke** [comment]
此问题已经修复，请升级到最新版。
https://github.com/yangzhongke/Zack.EFCore.Batch/issues/125
