### ISSUE TITLE
Async operations must take CancellationToken as parameter

### ISSUE THREAD

**Issue by busyscout** [yangzhongke/Zack.EFCore.Batch#7]
Async operations (e.g. ExecuteAsync) must take CancellationToken as parameter. Usually it is the last optional parameter.
So, you should change, for example, change 
```
Task<int> ExecuteAsync(bool ignoreQueryFilters = false) 
```
to 
```
Task<int> ExecuteAsync(bool ignoreQueryFilters = false, CancellationToken cancellationToken = default)
```

**Comment by yangzhongke** [comment]
Done. Please update to latest packages.
