### ISSUE TITLE
大佬，您好！批量插入不支持复杂对象属性。

### ISSUE THREAD

**Issue by paul0727** [yangzhongke/Zack.EFCore.Batch#74]
[Table("Post")]
    public class Post
    {

        [Key]
        public Guid Id { get; set; }

        public string Code { get; set; }

        public virtual Language Name { get; set; }

      
    }

    [Owned]
    public class Language
    {
        [MaxLength(400)]
        public string Cn { get; set; }
        [MaxLength(400)]
        public string En { get; set; }

        public Language()
        {

        }
        public Language(string cn, string en)
        {
            Cn = cn;
            En = en;
        }
    }

**Comment by kaixin1995** [comment]
sdgsd56gsd6g5s6dgsdgャクヤなどがミドっぱくラバニラサダウのブはとてもおいしそうな

**Comment by yangzhongke** [comment]
谢谢反馈，我会抽时间支持这个。

**Comment by yangzhongke** [comment]
抱歉，前阵子在跨国搬家，所以一直没处理。
刚才已经完成这个功能了，请升级到最新版。请反馈测试结果。

**Comment by yibey** [comment]
当对象是嵌套的onwed属性时目前有错误，我基于这个做了一些修改，总体思路 添加一个List<PropertyInfo> Properties 用于记录每个columname获取的 属性路径.原本想git直接提交，一直提示403是不是我没有权限提交。代码如下：
DbProp部分
`public class DbProp
    {
        public ValueConverter? ValueConverter { get; set; }
        public string ColumnName { get; set; }

        public Func<object, object?> GetValueFunc;
        //public PropertyInfo Property { get; set; }

        public List<PropertyInfo> Properties { get; set; }

        public Type PropertyType { get; set; }
    }`
  BulkInsertUtils部分  ，其中ParseDbProps方法重载了一个私有方法，其实这两者可以统一成一个方法。
`public static class BulkInsertUtils
    {
        public static bool IsOwnedProp(IEntityType entityType, PropertyInfo propInfo)
        {
            var propEntityType = entityType.Model.FindEntityType(propInfo.PropertyType);
            return propEntityType != null && propEntityType.IsOwned();
        }
        public static bool IsNavigationProp(IEntityType entityType, PropertyInfo propInfo)
        {
            return entityType.FindNavigation(propInfo) != null;
        }

        //https://github.com/yangzhongke/Zack.EFCore.Batch/issues/74
        static IEnumerable<DbProp> BuildDbPropsForOwnedType(DbContext context, IEntityType entityType, PropertyInfo propInfo)
        {
            //https://github.com/dotnet/efcore/issues/28241
            var propEntityType = context.Model.FindEntityType(propInfo.PropertyType, propInfo.Name, entityType);
            if(propEntityType==null)
            {
                propEntityType = context.Model.FindEntityType(propInfo.PropertyType);
            }
            var tableIdentifier = StoreObjectIdentifier.Table(propEntityType.GetTableName()!,null);
            foreach(var subProp in propInfo.PropertyType.GetProperties().Where(p=>p.CanRead))
            {
                var subPropEFProp = propEntityType.FindProperty(subProp.Name);
                string subPropColName = subPropEFProp!.FindColumn(tableIdentifier)!.Name;
                DbProp dbProp = new DbProp
                {
                    ColumnName = subPropColName,
                    GetValueFunc = (obj) => {
                        object? propValue = propInfo.GetValue(obj);
                        if(propValue==null)
                        {
                            return null;
                        }
                        object? subPropValue = subProp.GetValue(propValue);
                        return subPropValue;
                    },
                    PropertyType = subProp.PropertyType,
                    ValueConverter = subPropEFProp.GetValueConverter(),
                };
                yield return dbProp;
            }            
        }

        /// <summary>
        /// Get properties except for navigationProperties or  autogenerated ones
        /// </summary>
        /// <typeparam name="TEntity"></typeparam>
        /// <param name="dbCtx"></param>
        /// <returns></returns>
        public static DbProp[] ParseDbProps<TEntity>(DbContext dbCtx, IEntityType entityType, List<PropertyInfo> parentPropFields = null) where TEntity : class
        {

            List<DbProp> propFields = new List<DbProp>();
            //skip navigationProperties
            var props = entityType.ClrType.GetProperties().Where(p => IsOwnedProp(entityType, p) || !IsNavigationProp(entityType, p) && p.CanRead);

            if (parentPropFields == null)
            {
                parentPropFields = new List<PropertyInfo>();
            }

            foreach (var prop in props)
            {
                if (IsOwnedProp(entityType, prop))
                {
                    var ownedNavigation = entityType.FindNavigation(prop);
                    var newParentFs = new List<PropertyInfo>();
                    newParentFs.AddRange(parentPropFields);
                    newParentFs.Add(prop);
                    propFields.AddRange(ParseDbProps(ownedNavigation.TargetEntityType, newParentFs));

                }
                else
                {
                    string propName = prop.Name;
                    var efProp = entityType.FindProperty(propName);
                    if (efProp == null)//this property is not mapped
                    {
                        continue;
                    }
                    //skip the columns those are autogenerated
                    if (efProp.ValueGenerated == ValueGenerated.OnAdd
                        || efProp.ValueGenerated == ValueGenerated.OnAddOrUpdate)
                    {
                        //fix issue: https://github.com/yangzhongke/Zack.EFCore.Batch/issues/24
                        if (efProp.ClrType != typeof(Guid) && efProp.ClrType != typeof(Guid?))
                        {
                            continue;
                        }
                    }
                    StoreObjectIdentifier? storeObjectIdentifier = StoreObjectIdentifier.Create(entityType, StoreObjectType.Table);
                    string dbColName = "";
                    if (storeObjectIdentifier.HasValue)
                    {
                        dbColName = efProp.GetColumnName(storeObjectIdentifier.Value);
                    }
                    else
                    {
                        dbColName = efProp.GetDefaultColumnBaseName();

                    }

                    var propertyRoutes = new List<PropertyInfo>();
                    propertyRoutes.AddRange(parentPropFields);
                    propertyRoutes.Add(prop);
                    DbProp dbProp = new DbProp
                    {
                        ColumnName = dbColName,
                        //Property = prop,
                        //GetValueFunc = (obj) => prop.GetValue(obj),
                        //PropertyType = prop.PropertyType,
                        Properties = propertyRoutes,
                        ValueConverter = efProp.GetValueConverter(),
                    };
                    propFields.Add(dbProp);
                }
            }
            return propFields.ToArray();
        }



        private static DbProp[] ParseDbProps(IEntityType entityType, List<PropertyInfo> parentPropFields = null)
        {

            List<DbProp> propFields = new List<DbProp>();
            //skip navigationProperties
            var props = entityType.ClrType.GetProperties().Where(p => IsOwnedProp(entityType, p) || !IsNavigationProp(entityType, p) && p.CanRead);

            if (parentPropFields == null)
            {
                parentPropFields = new List<PropertyInfo>();
            }

            foreach (var prop in props)
            {
                if (IsOwnedProp(entityType, prop))
                {
                    var ownedNavigation = entityType.FindNavigation(prop);
                    var newParentFs = new List<PropertyInfo>();
                    newParentFs.AddRange(parentPropFields);
                    newParentFs.Add(prop);

                    propFields.AddRange(ParseDbProps(ownedNavigation.TargetEntityType, newParentFs));

                }
                else
                {
                    string propName = prop.Name;
                    var efProp = entityType.FindProperty(propName);
                    if (efProp == null)//this property is not mapped
                    {
                        continue;
                    }
                    //skip the columns those are autogenerated
                    if (efProp.ValueGenerated == ValueGenerated.OnAdd
                        || efProp.ValueGenerated == ValueGenerated.OnAddOrUpdate)
                    {
                        //fix issue: https://github.com/yangzhongke/Zack.EFCore.Batch/issues/24
                        if (efProp.ClrType != typeof(Guid) && efProp.ClrType != typeof(Guid?))
                        {
                            continue;
                        }
                    }
                    StoreObjectIdentifier? storeObjectIdentifier = StoreObjectIdentifier.Create(entityType, StoreObjectType.Table);
                    string dbColName = "";
                    if (storeObjectIdentifier.HasValue)
                    {
                        dbColName = efProp.GetColumnName(storeObjectIdentifier.Value);
                    }
                    else
                    {
                        dbColName = efProp.GetDefaultColumnBaseName();

                    }

                    var propertyRoutes = new List<PropertyInfo>();
                    propertyRoutes.AddRange(parentPropFields);
                    propertyRoutes.Add(prop);
                    DbProp dbProp = new DbProp
                    {
                        ColumnName = dbColName,
                        //Property = prop,
                        //GetValueFunc = (obj) => prop.GetValue(obj),
                        //PropertyType = prop.PropertyType,
                        Properties = propertyRoutes,
                        ValueConverter = efProp.GetValueConverter(),
                    };
                    propFields.Add(dbProp);
                }
            }
            return propFields.ToArray();
        }


        /// <summary>
        /// Build DataTable for items
        /// </summary>
        /// <typeparam name="TEntity"></typeparam>
        /// <param name="dbSet"></param>
        /// <param name="items"></param>
        /// <returns></returns>
        public static DataTable BuildDataTable<TEntity>(DbContext dbCtx, DbSet<TEntity> dbSet, 
            IEnumerable<TEntity> items) where TEntity : class
        {
            var entityType = dbSet.EntityType;
            var dbProps = ParseDbProps<TEntity>(dbCtx,entityType);            
            DataTable dataTable = new DataTable();
            foreach (var dbProp in dbProps)
            {
                string columnName = dbProp.ColumnName;
                Type propType = dbProp.Properties.Last().PropertyType;
                DataColumn col;
                bool isNullable;
                var valueConverter = dbProp.ValueConverter;
                if (valueConverter != null)
                {
                    var providerType = valueConverter.ProviderClrType;
                    isNullable = BatchUtils.IsNullableType(providerType);
                    if(isNullable)
                    {
                        col = dataTable.Columns.Add(columnName, 
                            providerType.GenericTypeArguments[0]);
                        //fix: https://stackoverflow.com/questions/40953738/define-a-column-as-nullable-in-system-data-datatable
                        col.AllowDBNull = true;
                    }
                    else
                    {
                        col = dataTable.Columns.Add(columnName, providerType);
                    }                    
                }
                else
                {
                    isNullable = BatchUtils.IsNullableType(propType);
                    if(isNullable)
                    {
                        col = dataTable.Columns.Add(columnName,
                            propType.GenericTypeArguments[0]);
                        col.AllowDBNull = true;
                    }
                    else
                    {
                        col = dataTable.Columns.Add(columnName, propType);
                    }                    
                }             
            }
            foreach (var item in items)
            {
                DataRow row = dataTable.NewRow();
                foreach (var dbProp in dbProps)
                {
                    //object? value = dbProp.Property.GetValue(item);
                    //object? value = dbProp.GetValueFunc(item);
                    object? value = item;
                    foreach (var route in dbProp.Properties)
                    {
                        value = route.GetValue(value);
                        if (value == null)//目标值为null直接跳出循环
                        {
                            break;
                        }
                    }
                    //fix https://github.com/yangzhongke/Zack.EFCore.Batch/issues/41
                    // and https://github.com/yangzhongke/Zack.EFCore.Batch/issues/23
                    //ValueConverter begin
                    var valueConverter = dbProp.ValueConverter;
                    if(valueConverter != null)
                    {
                        value = valueConverter.ConvertToProvider(value);
                    }
                    //ValueConverter end
                    if (value==null)
                    {
                        value = DBNull.Value;
                    }
                    row[dbProp.ColumnName] = value;
                }
                dataTable.Rows.Add(row);
            }
            return dataTable;
        }
    }`
实体如下：
`  public class Article
	{
		public long Id { get; set; }
		public string Title { get; set; }
		public string Content { get; set; }
		public List<Comment> Comments { get; set; } = new List<Comment>();
		public MultiString Remarks { get; set; }
	}
public class MultiString
    {
        public string? Chinese { get; set; }
        public string? English { get; set; }

        public SubMultiString Second { get; set; }
    }

    public class SubMultiString
    {
        public string? Name { get; set; }
    }`

**Comment by yangzhongke** [comment]
嵌套owned什么意思？owned属性里又有属性是owned？
你不是项目组成员，所以不能直接提交代码，但是你可以先fork到自己的库中，然后在你的库中修改、commit，然后你再提交Pull Request到我的库，我review之后就可以把你的修改合并了。具体怎么弄（github提交PR）请查看网上资料。

**Comment by yibey** [comment]
是owned 里又包含了owned场景。我试一下按照你说的方法来提交。
