### ISSUE TITLE
NuGet上的包没有发现支持NET Standard 2.1

### ISSUE THREAD

**Issue by findersky** [yangzhongke/Zack.EFCore.Batch#78]
NuGet上的包没有发现支持NET Standard 2.1

**Comment by yangzhongke** [comment]
EntityFrameworkCore是只支持.net core，并不支持.net standard。我的库依赖于EntityFrameworkCore，所以不支持.net standard。

**Comment by yangzhongke** [comment]
你为什么需要它支持NET Standard？毕竟EntityFrameworkCore都不支持NET Standard
