### ISSUE TITLE
Regression with 6.1.0 on BatchUpdateBuilder.Set()

### ISSUE THREAD

**Issue by begerard** [yangzhongke/Zack.EFCore.Batch#79]
Hi,

By upgrading from 6.0.15 to 6.1.0 I now have an exception with the untyped overload "Set(string name, object value)".

In the specific case where the target property is nullable, it now throw on both not-null and null values:
``Invalid cast from 'System.Int32' to 'System.Nullable`1[[System.Int32...]]`` and ``Null object cannot be converted to a value type.``

**Comment by begerard** [comment]
I explored a bit your code on this method, and it does come from the fix for my issue last week. I'm not sure why you commented this code https://github.com/yangzhongke/Zack.EFCore.Batch/blame/main/Zack.EFCore.Batch/Internal/BatchUpdateBuilder.cs#L78 but it looks like you do need it.

In addition, I use this untyped overload because I use the batched Set in a reflective method, and the code to convert a PropertyInfo to the lambda needed by EF is not trivial (and this bug only proves it!). Can you add an intermediary overload below this one with the signature `BatchUpdateBuilder<TEntity> Set(PropertyInfo propInfo,  object value)` and make the `BatchUpdateBuilder<TEntity> Set(string name, object value)` one call it? It would save a call to `.GetProperty(name)` in my use case.

**Comment by yangzhongke** [comment]
Bug fixed, please update it to the latest version.

```
await ctx.BatchUpdate<Book>()
.Set("Price", null)
.ExecuteAsync();

await ctx.BatchUpdate<Book>()
.Set(b=>b.Price,b=> null)
.ExecuteAsync();
```
