### ISSUE TITLE
Support for NpgSql Schema

### ISSUE THREAD

**Issue by rfrancisco** [yangzhongke/Zack.EFCore.Batch#8]
Please add support for the schemas . Right now the library assumes that all tables reside in the default database schema and that may not be the case.

Example of an EF Entity with a custom Schema:
```csharp
[Table("persons", Schema = "catalog")]
public class Person {
    [Key]
    public int Id { get; set; }
}
```

In order to delete from this table the query would need to be:
```sql
DELETE FROM catalog.persons WHERE ....
```

Right now it's trying to do:
```sql
DELETE FROM persons WHERE ....
```

This causes an error saying the table 'persons' does not exist.

I'm testing with the NpgSql version.

**Comment by yangzhongke** [comment]
Thanks for you feedback. I'll check and fix it today.

**Comment by yangzhongke** [comment]
bug fixed. please update the packages to the latest version(>=1.2.5)

**Comment by rfrancisco** [comment]
It works now. Thanks!
