### ISSUE TITLE
where 条件

### ISSUE THREAD

**Issue by 273168121** [yangzhongke/Zack.EFCore.Batch#82]
await  _dbContext.BatchUpdate<TbTest>().Set(x => x.Code, "3333333")
              .Where(x =>string.IsNullOrEmpty(x.Name))
                .ExecuteAsync();

          

这种的好像where 条件没解析吧？

**Comment by yangzhongke** [comment]
我测试没问题呀
![image](https://user-images.githubusercontent.com/13821363/182094163-6b6b934e-0658-4803-a3df-cdb3d89b3b9a.png)


![image](https://user-images.githubusercontent.com/13821363/182094257-2f277512-11d4-424d-a73f-abdb6e2a74d5.png)

**Comment by 273168121** [comment]
不知道呢，我用的mysql,我试就判定为空的条件不行，
`   modelBuilder.Entity<TbTest>(x =>
            {
                x.ToTable("TB_TEST");
                x.HasKey(x => x.Id);
                x.Property(x => x.Id).HasColumnName("id");
                x.Property(x => x.Name).HasColumnName("name");
                x.Property(x => x.Code).HasColumnName("code");
                x.Property(x => x.Time).HasColumnName("time");
            });

   public class TbTest
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }

        public DateTime? Time { get; set; }
    }

    transaction=  await  _dbContext.Database.BeginTransactionAsync(); 
          await  _dbContext.BatchUpdate<TbTest>().Set(x => x.Code, "3333333")
              .Where(x =>string.IsNullOrEmpty(x.Name))
                .ExecuteAsync();
            await transaction.CommitAsync();
`

**Comment by yangzhongke** [comment]
生成的SQL语句是什么？或者报什么错？

**Comment by 273168121** [comment]
没有报错，我看数据库的，我不知道这个日志在哪打开

**Comment by 273168121** [comment]
https://gitee.com/Chareree/netcoremydemo.git  代码在这里你看看呢？

**Comment by yangzhongke** [comment]
那还是请先自己研究一下如何通过日志查看ef core执行的sql，确认是我的组件执行sql错误吧

**Comment by 273168121** [comment]
ef的sql日志能看到，看不这个组件的日志，我确认好几遍了没问题 我where条件写死==“12”更新过来了，那个就是不行

**Comment by yangzhongke** [comment]
这个组件的sql也是记录到日志的。你可以试着调整一下日志的level或者看看控制台日志。总之，肯定能看到的

**Comment by yangzhongke** [comment]
你是更新不了数据库中属性值为null的还是“”的？

**Comment by 273168121** [comment]
数据库where 条件那列值为空在数据库中不是“ ” 或“”，我要更新条件为空的，

**Comment by yangzhongke** [comment]
你用的是.net6吧。你的属性声明为string，efcore认为string不可以为null，所以ef core 只会翻译成=""不会翻译成 =“” or is null。你需要把属性改成string?。

**Comment by 273168121** [comment]
是的

**Comment by yangzhongke** [comment]
ok。解决了就好
