### ISSUE TITLE
BatchUpdate的时候，全局查询过滤器无法获取到注入的租户信息

### ISSUE THREAD

**Issue by FeiCunXinTai** [yangzhongke/Zack.EFCore.Batch#84]
ServiceCollection services = new ServiceCollection();

services.AddScoped<ContextManager>();
services.AddScoped<WlcSession>();
services.AddDbContext<TestDbContext>(ServiceLifetime.Scoped).AddUnitOfWork<TestDbContext>();

using (var sp = services.BuildServiceProvider())
{
    var session = sp.GetService<WlcSession>();
    session.IsAuthrizaSuccess = true;
    session.UserName = "638051032714457088";
    session.CTCloudUserId = "638051032714457088";
    session.TenantId = "650058347168673792";
    session.ProjectId = 745275920126062592;

    using (var uow = sp.GetRequiredService<IUnitOfWork<TestDbContext>>())
    {
        using var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
        var repo = uow.GetRepository<Project_Info>();
        //await repo.BatchDeleteAsync(x => x.Id == 123456);
        await uow.DbContext.BatchUpdate<Project_Info>().Set(q => q.Is_Soft_Deleted, q => false).Where(q => q.Id.Value == 312475030403461).ExecuteAsync();
        scope.Complete();
    }
}

大佬，这次准备了一个百度网盘的链接，里面有可测试的控制台，还有建库和测试数据的SQL。修改下连接字符串就可以测试了。
谢谢大佬！

**Comment by FeiCunXinTai** [comment]
链接：https://pan.baidu.com/s/1PeHUpJq6A5PfLyQNIzRIuQ 
提取码：jc1u

**Comment by yangzhongke** [comment]
谢谢，我终于能重现这个问题了，之前也有人反馈过。
在QueryFilter中的表达式引用DbContext中的属性就会造成这个问题。这个涉及到EF Core的翻译机制，还没想到思路。最近比较忙，我有时间再去研究怎么解决。
目前只能先通过ExecuteAsync的ignoreQueryFilters设置false来让这个组件忽略全局QueryFilter，然后你手动设置过滤条件。

**Comment by yangzhongke** [comment]
我在这里记个关于自己解决这个问题想法的一个笔记：不再用BatchEFExtensions.Parse的方法来拆解分析SQL语句，而是直接对queryable.ToQueryString()的SQL做语法分析。

```
SET @__ef_filter__testDateTime_0 = TIMESTAMP '2022-08-09 16:54:53.691911';

SELECT `t`.`Price`, NULL
FROM `T_Books` AS `t`
WHERE ((`t`.`PubTime` > CURRENT_TIMESTAMP()) AND (`t`.`PubTime` > @__ef_filter__testDateTime_0)) AND (`t`.`AuthorName` IS NULL OR (`t`.`AuthorName` = ''))
```

**Comment by FeiCunXinTai** [comment]
谢谢大佬，用到租户的表不多，先手动忽略全局QueryFilter
大佬有空再看看这个问题

**Comment by l2999019** [comment]
我花了点时间 找到了这个参数应该怎么获取
![image](https://github.com/user-attachments/assets/929eb372-420c-451d-941a-91afaf16567c)
比较蛋疼 需要通过反射私有方法,代码如下:
`  var enumerator = queryable.Provider.Execute<IEnumerable>(queryable.Expression).GetEnumerator();
  var queryContextrq = enumerator.Private<RelationalQueryContext>("_relationalQueryContext");
  var parameterValues = queryContextrq?.ParameterValues;
  if (parameterValues != null) {
      foreach (var parameterValue in parameterValues)
      {
          queryContext.AddParameter(parameterValue.Key, parameterValue.Value);
      }
  }`
我加到BatchEFExtensions.Parse里面 Optimize方法之前
执行Optimize方法的时候 就不会出现报错了
可以正常生成Updata和delete的语句

**Comment by yangzhongke** [comment]
@l2999019  谢谢，尽量减少对私有成员的访问，所以就不支持这个了。

**Comment by l2999019** [comment]
好吧 那我只能自己开个库了 因为我们也有用到全局查询过滤
