### ISSUE TITLE
MySql批量删除功能，生成的Sql语句包含全表字段，导致执行效率很低。

### ISSUE THREAD

**Issue by chenyunfei7950** [yangzhongke/Zack.EFCore.Batch#87]
![image](https://user-images.githubusercontent.com/12883168/188284779-6765ad06-0d76-4f94-9750-a5c6ed3c5a4a.png)

**Comment by yangzhongke** [comment]
已经修复，请更新到最新版。

**Comment by chenyunfei7950** [comment]
厉害👍
