### ISSUE TITLE
ABP的框架中用这个组件 批量插入时 会报错

### ISSUE THREAD

**Issue by l2999019** [yangzhongke/Zack.EFCore.Batch#88]
错误信息:
 The transaction associated with this command is not the connection's active transaction; see https://fl.vu/mysql-trans

代码如下:
`                    var context_details = _detailServices.GetDbContextAsync().Result;

                    _services.InsertAsync(accountVoucherEntity); //此条可以正常插入

                    context_details.BulkInsert(detailList); //这里不行

                    foreach (var entity in detailList)
                    {
                        _entityChangeEventHelper.TriggerEntityCreatingEventAsync(entity);
                        _entityChangeEventHelper.TriggerEntityCreatedEventOnUowCompletedAsync(entity);
                    }`

**Comment by yangzhongke** [comment]
应该你的“InsertAsync”这个操作里面把connection或者context关闭了导致的
