### ISSUE TITLE
jsonb类型的实体批量插入报错

### ISSUE THREAD

**Issue by zhangxiaofanGit** [yangzhongke/Zack.EFCore.Batch#89]
System.NotSupportedException
  HResult=0x80131515
  Message=The CLR type System.Text.Json.JsonElement isn't natively supported by Npgsql or your PostgreSQL. To use it with a PostgreSQL composite you need to specify DataTypeName or to map it, please refer to the documentation.
  Source=Npgsql
  StackTrace:
   在 Npgsql.TypeMapping.ConnectorTypeMapper.GetByClrType(Type type)
   在 Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   在 Npgsql.NpgsqlBinaryImporter.<Write>d__27`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Npgsql.NpgsqlBinaryImporter.Write[T](T value)
   在 System.Linq.NpgSqlBulkInsertExtensions.BuildImporter[TEntity](DbContext dbCtx, NpgsqlConnection pgConn, IEnumerable`1 items)
   在 System.Linq.NpgSqlBulkInsertExtensions.BulkInsert[TEntity](DbContext dbCtx, IEnumerable`1 items)
   在 PLM.Service.CommomItem.FMEA.ItemDataService.BulkInsertIterationModels(List`1 models) 在 E:\Code\plm-net-commonitem\PLM.Service.CommomItem\ItemDataService.cs 中: 第 244 行
   在 PLM.Application.CommomItem.ItemDataClient.InitIteration(List`1 models) 在 E:\Code\plm-net-commonitem\PLM.Application.CommomItem\ItemDataClient.cs 中: 第 381 行
   在 PLM.WebApi.CommonItem.Controllers.ItemDataController.InitIteration(List`1 models) 在 E:\Code\plm-net-commonitem\PLM.WebApi.CommonItem\Controllers\ItemDataController.cs 中: 第 189 行
   在 Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   在 Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    PLM.Service.CommomItem.FMEA.ItemDataService.BulkInsertIterationModels(System.Collections.Generic.List<PLM.Serv

**Comment by yangzhongke** [comment]
请提供一个能重现这个问题的最简单的项目代码。谢谢
