### ISSUE TITLE
Table should be specified

### ISSUE THREAD

**Issue by seagullua** [yangzhongke/Zack.EFCore.Batch#9]
Current syntax:

`dbContext.DeleteRangeAsync<Book>(...)`

The issue will appear if we have two tables with a class Book. It won't be clear from which table the items will be deleted (if any). There is a better approach to specify the collection from which the entries should be removed.

`dbContext.Books.DeleteRangeAsync(...)`

**Comment by yangzhongke** [comment]
I'm working on it, I'll improve it today.

**Comment by yangzhongke** [comment]
Done.
Please update to the latest version.
Usage:
await ctx.Books2.DeleteRangeAsync(ctx, b => b.AuthorName == "zack");
await ctx.Books2.BatchUpdate(ctx)
	.Set(b => b.Price, b => 3.0)
	.Where(b => b.Id > 5)
	.ExecuteAsync();

**Comment by yangzhongke** [comment]
Actually, I have no idea about how to use a single entity type in two Dbsets, so I cannot verify my code. Can you let me know how to do it, and verify my solution work or not.
Please let me know the result.
Thanks.
