### ISSUE TITLE
MySql Pomelo - Mapping Parent child

### ISSUE THREAD

**Issue by sathyakrishnan** [yangzhongke/Zack.EFCore.Batch#91]
Hi,
We're trying to use the package with MySQL and Pomelo. We have a parent -> child1 -> child2 -> child3 scenario.
Does BulkInsert handles child entities and inserts data ?

**Comment by yangzhongke** [comment]
Sorry, it doesn't support  inheritance hierarchy, so they should be inserted explicitly.
