### ISSUE TITLE
能不能提供工厂模式，可以将sqlserver、mysql、sqllit这个几个包都导入进去？

### ISSUE THREAD

**Issue by girg** [yangzhongke/Zack.EFCore.Batch#93]
现在同时导入sqlserver、mysql、sqllit会冲突。能不能提供一种方式在项目里面把这几个包同时安装，同时支持多个数据库？

**Comment by yangzhongke** [comment]
https://github.com/yangzhongke/Zack.EFCore.Batch/issues/56
