### ISSUE TITLE
升级.net7

### ISSUE THREAD

**Issue by a645010545** [yangzhongke/Zack.EFCore.Batch#95]
Method 'GetCommand' in type 'Zack.EFCore.Batch.MSSQL.Internal.ZackQuerySqlGenerator_MSSQL' from assembly 'Zack.EFCore.Batch.MSSQL, Version=1.6.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by a645010545** [comment]
Method 'GetCommand' in type 'Zack.EFCore.Batch.MSSQL.Internal.ZackQuerySqlGenerator_MSSQL' from assembly 'Zack.EFCore.Batch.MSSQL_NET6, Version=6.1.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by yangzhongke** [comment]
.NET 7已经内置了批量删除、更新的功能，因此我这个库光荣退休，不再计划支持.NET 7
[https://github.com/yangzhongke/Zack.EFCore.Batch/issues/95#:~:text=Method%20%27GetCommand%27%20in%20type%20%27Zack.EFCore.Batch.MSSQL.Internal.ZackQuerySqlGenerator_MSSQL%27%20from%20assembly%20%27Zack.EFCore.Batch.MSSQL%2C%20Version%3D1.6.3.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3Dnull%27%20does%20not%20have%20an%20implementation.](https://github.com/yangzhongke/Zack.EFCore.Batch/issues/95#:~:text=Method%20%27GetCommand%27%20in%20type%20%27Zack.EFCore.Batch.MSSQL.Internal.ZackQuerySqlGenerator_MSSQL%27%20from%20assembly%20%27Zack.EFCore.Batch.MSSQL%2C%20Version%3D1.6.3.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3Dnull%27%20does%20not%20have%20an%20implementation.)

**Comment by yangzhongke** [comment]
本项目提供了对.NET7的限制性支持，请访问 https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/README_CN_NET7.md
