### ISSUE TITLE
当多个更新值写成常量值一样时会报错！

### ISSUE THREAD

**Issue by weiwin123** [yangzhongke/Zack.EFCore.Batch#97]
_DataContext.BatchUpdate<TestModel>().Where(t => t.Id == order.Id).Set(t => t.PayStatus, t => 4).Set(t=>t.State,t=> 4).ExecuteAsync()

One or more errors occurred. (The count of columns initializersSet and ProjectionSQL should equal

**Comment by yangzhongke** [comment]
抱歉，无法重现这个问题，请提供一个能重现一个这个问题的最简单的项目（不要上传整个项目，只要弄一个能重现问题的小项目即可）。可以把项目打包传上来或者放到github

**Comment by weiwin123** [comment]
抱歉，我单独建了个项目去复现，结果也没复现出来
