### ISSUE TITLE
Method not found: Void MySqlConnector.MySqlBulkCopy.WriteToServer

### ISSUE THREAD

**Issue by Calm3890** [yangzhongke/Zack.EFCore.Batch#99]
After updating the nuget, context.bulkinsert return 'Method not found: Void MySqlConnector.MySqlBulkCopy.WriteToServer'
Please help,
Thankyou

**Comment by yangzhongke** [comment]
Please make sure that you use the latest version of MySqlConnector. Or you can install it explicitly:
Install-Package MySqlConnector -Version 2.2.0

**Comment by Calm3890** [comment]
My version of MySqlConnector is already 2.2.0 but it still returns '"Method not found: 'Void MySqlConnector.MySqlBulkCopy.WriteToServer(System.Data.DataTable)'."'

**Comment by yangzhongke** [comment]
The latest version of Zack.EFCore.Batch.MySQL.Pomelo is  1.6.3, did you try to update it?
If there is still a problem, could you please let me know how to reproduce it? You can upload a simple project which can reproduce it

**Comment by Calm3890** [comment]
i've tried it already seems like, the problem is on Microsoft.Extensions.DependencyInjection.Abstractions which it needs V.6 but Zack.EFCore.Batch.MySQL.Pomelo is only compatible with V.5, is there any upgrade to match the required dependencies?
<img width="2024" alt="Screenshot 2022-12-06 at 16 09 30" src="https://user-images.githubusercontent.com/36410028/205868640-f8da4a02-be42-48c6-9cdb-0a7dc9cd6fec.png">

**Comment by yangzhongke** [comment]
.NET 5 and .NET 6 users should use dedicated versions, please check
[https://github.com/yangzhongke/Zack.EFCore.Batch](https://github.com/yangzhongke/Zack.EFCore.Batch)

![image](https://user-images.githubusercontent.com/13821363/206010165-9ba9f17d-4b58-4a6a-bfde-e0690600ffe5.png)
